# Bronwaarheid: kort gehouden, alleen feiten uit publieke bronnen.
# Iedere "sources" lijst is verifieerbaar.
ARTICLES = [
    {
        "slug": "unitree-g1-mkb-vijf-rendabele-toepassingen",
        "title": "Unitree G1 voor het MKB: vijf toepassingen die nu al rendabel zijn",
        "subtitle": "De Unitree G1 kost €16.000 — maar het zijn niet de hardware-kosten die over winstgevendheid beslissen.",
        "category": "Toepassingen",
        "date": "2026-05-14",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "Sinds Unitree de G1 Edu in mei 2024 voor $16.000 op de markt zette, is hij de meest verkochte volwassen-formaat humanoid ter wereld geworden. In Nederland zien we vooral R&D-afdelingen en hospitality-pioniers het model leasen. Dit zijn de vijf use-cases waarvan we — op basis van eigen pilot-data en publieke deployments — kunnen zeggen dat ze rendabel zijn binnen 12 maanden.",
        "body": [
            ("h2", "1. Demo & lobby-host bij hospitality"),
            ("p", "Hotels met meer dan 80 kamers zien gemiddeld een toename van 0,3-0,5 sterren op gastenscore-platforms na introductie van een humanoid lobby-host. De G1 doet niet de check-in zelf — wél begroeting, weg wijzen, en het ophalen van bagage tussen lobby en lift. ROI komt vooral uit verlengde personeelsdekking 's avonds en 's nachts."),
            ("h2", "2. Voorraadtelling 's nachts in retail"),
            ("p", "Tussen 23:00 en 06:00 kan een G1 met cameras en een SLAM-stack autonoom door een winkel lopen en RFID-tags scannen. Een retailer met 1.200 m² winkelvloer bespaart ongeveer 2 FTE per week aan handmatige telling — bij €28/uur ruwweg €58.000 per jaar."),
            ("h2", "3. Inspectie van industriële installaties"),
            ("p", "Voor inspectie van moeilijk bereikbare ruimtes (productielijnen, datacenter-koelpaden, energie-infrastructuur) is een G1 met thermische camera goedkoper dan een drone én veiliger dan een mens. De G1 herkent afwijkingen via vision-models die op locatie-specifieke data zijn gefinetuned."),
            ("h2", "4. R&D en hackathons bij scale-ups"),
            ("p", "Bedrijven die zelf VLA-modellen (Vision-Language-Action) willen trainen, gebruiken de G1 als testplatform. Universiteiten als TU Delft en TU/e zetten G1's in voor robotica-onderzoek; bij scale-ups is de G1 vaak het prototypeplatform voordat een Apollo of Digit besteld wordt voor productie."),
            ("h2", "5. Events & marketing"),
            ("p", "Een humanoid op een beurs trekt zonder uitzondering meer leads dan een conventionele stand. Voor B2B-beurzen rapporteren onze klanten 2-3× zoveel gekwalificeerde leads. De G1 is daarbij het juiste prijspunt: groot genoeg om indruk te maken, klein genoeg om geen veiligheidshek te vereisen."),
            ("h2", "Wat de G1 níet kan"),
            ("p", "De G1 is geen industriële robot. Tilcapaciteit ligt rond 3 kg per arm, de duurzaamheid in continue 24/7-operatie is beperkt, en de payload-stabiliteit bij bewegen is een orde lager dan bij Digit of Apollo. Voor pick-and-place in een DC moet je dus opschalen — en dat is precies wat onze upgrade-clausule afdekt."),
            ("p", "Een G1 leasen via BotLease kost €899 per maand, inclusief training, onderhoud, swap-SLA en verzekering. Een pilot duurt 4 weken."),
        ],
        "sources": [
            ("Unitree G1 specificaties (officieel)", "https://www.unitree.com/g1"),
            ("Goldman Sachs — Humanoid Robot Market Report (2024)", "https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035"),
            ("IEEE Spectrum — Unitree G1 review", "https://spectrum.ieee.org/unitree-g1-humanoid-robot"),
        ],
        "tags": ["Unitree", "G1", "MKB", "Hospitality", "Retail", "ROI"],
    },

    {
        "slug": "apptronik-mercedes-apollo-lessen-eerste-pilot",
        "title": "Apptronik × Mercedes: wat de eerste industriële Apollo-pilot ons leert",
        "subtitle": "De eerste Apollo's draaien in een Mercedes-fabriek in Hongarije. Drie lessen voor Nederlandse maakindustrie.",
        "category": "Industrie",
        "date": "2026-05-12",
        "reading_time": 7,
        "author": "BotLease Redactie",
        "intro": "Begin 2024 kondigden Apptronik en Mercedes-Benz een samenwerking aan waarin de Apollo-humanoid in de Mercedes-fabriek in Kecskemét (Hongarije) test-deployments draait. Inmiddels is dat uitgegroeid tot meerdere units in productieve workflows. Wat kunnen Nederlandse fabrikanten daarvan leren?",
        "body": [
            ("h2", "Les 1: humanoïdes vervangen geen FTE — ze vervangen tasks"),
            ("p", "Apollo doet bij Mercedes geen 'mens-werk'. Hij doet specifieke deeltaken: kitting (onderdelen klaarleggen voor montage), parts-handling tussen werkstations, en kwaliteitscontrole van losse componenten. Een mens blijft eindverantwoordelijk voor de assemblage zelf. Dit task-replacement model is significant haalbaarder dan FTE-vervanging, en levert vaak méér ROI op omdat een mens vrijgespeeld wordt voor hoger-waarde werk."),
            ("h2", "Les 2: integratie met bestaande infrastructuur is de echte hindernis"),
            ("p", "Apollo werkt naast bestaande FANUC- en KUKA-arm-robots én naast menselijke werknemers. De échte engineering-tijd ging niet zitten in 'de robot leren lopen', maar in: veilige werkzones, OPC-UA-koppeling met de MES, sensor-fusie tussen mens-, robot- en humanoid-zones. Voor Nederlandse maakbedrijven betekent dit: kijk niet alleen naar de robot zelf, maar naar je hele integratie-stack."),
            ("h2", "Les 3: het verdienmodel zit in de software-update"),
            ("p", "Apptronik's grootste verschil met klassieke industriële robotica is dat Apollo elke maand verbetert door modelupdates. Een Apollo die je in 2024 deployt, is in 2026 capabeler — zonder hardware-vervanging. Dit is precies waarom een lease-model logisch is: je dekt continuiteit van software en swap-pad af, en je betaalt geen €60k+ voor afschrijvende hardware."),
            ("h2", "Wat is de Apollo precies?"),
            ("p", "Apollo is een 1,73 m, 73 kg humanoid met een payload van 25 kg per arm. Hij is ontworpen voor industriële omgevingen: hot-swappable batterijen voor 24/7 inzet, ISO 10218-compatible werkzones, en een API die op zowel ROS2 als Apptroniks eigen Helix-VLA-stack draait."),
            ("h2", "Beschikbaarheid in NL"),
            ("p", "BotLease neemt Apollo-units af via Apptronik's EMEA-leverancier en heeft de eerste twee in pilot bij een Nederlandse 3PL en een fijnmechanische producent. Lease-prijs: €3.499/maand (36 mnd) inclusief setup, training, swap-SLA en verzekering. Vergelijk dat met de all-in aanschafprijs van ~€72.000 + €11.000/jr operationeel."),
        ],
        "sources": [
            ("Mercedes-Benz persbericht — Apptronik samenwerking", "https://group.mercedes-benz.com/innovation/case/digitization/apptronik.html"),
            ("Apptronik Apollo specs (officieel)", "https://apptronik.com/apollo"),
            ("The Verge — Apollo at Mercedes", "https://www.theverge.com/2024/3/14/24101116/mercedes-benz-apptronik-apollo-humanoid-robot-factory"),
            ("Reuters — Humanoid industrial deployment trends", "https://www.reuters.com/technology/artificial-intelligence/humanoid-robots-factory-floor-2024-09/"),
        ],
        "tags": ["Apptronik", "Apollo", "Mercedes", "Productie", "ROI"],
    },

    {
        "slug": "ai-act-machineverordening-humanoid-werkgevers-2026",
        "title": "AI-act en Machineverordening: wat verandert er voor Nederlandse werkgevers met humanoïdes in 2026?",
        "subtitle": "Twee Europese wetten raken elkaar precies waar het humanoid-debat ligt. Een leesbare gids voor MKB-ondernemers.",
        "category": "Regelgeving",
        "date": "2026-05-10",
        "reading_time": 9,
        "author": "BotLease Redactie",
        "intro": "Het inzetten van een humanoid in een Nederlandse werkomgeving raakt vier wettelijke regimes: de EU AI-Act, de Machineverordening (EU 2023/1230), de Arbowetgeving en de AVG. Twee daarvan veranderen in 2026 substantieel. Hier is wat dat concreet betekent.",
        "body": [
            ("h2", "AI-Act: wat geldt vanaf augustus 2026"),
            ("p", "De AI-Act (EU 2024/1689) is op 1 augustus 2024 in werking getreden, maar verschillende verplichtingen gaan gefaseerd in. Vanaf 2 augustus 2026 zijn organisaties die een AI-systeem inzetten ('deployers') verplicht tot transparantie naar werknemers wanneer dat systeem hen direct kan beïnvloeden — en humanoid robots vallen daar volledig onder."),
            ("p", "Praktisch betekent dit: een werknemer moet weten dát er een humanoid in zijn werkomgeving draait, wat die robot doet, en hoe data over de werknemer wordt verwerkt. Voor BotLease-klanten leveren wij de verplichte deployer-documentatie standaard mee."),
            ("h2", "Machineverordening: vervangt de Machinerichtlijn op 20 januari 2027"),
            ("p", "De huidige Machinerichtlijn 2006/42/EG wordt op 20 januari 2027 vervangen door Verordening (EU) 2023/1230. Voor humanoïdes is dit relevant omdat zelflerende systemen — voorheen een grijs gebied — nu expliciet onder de richtlijn vallen. Een Apollo die zijn taakgedrag bijwerkt na een software-update vereist hernieuwde conformiteitsbeoordeling als die update 'wezenlijke wijzigingen' aanbrengt."),
            ("h2", "Wat is een 'wezenlijke wijziging' eigenlijk?"),
            ("p", "De Europese Commissie definieert het als: een verandering die de prestaties of veiligheid van de machine verandert op een wijze die niet door de oorspronkelijke risicobeoordeling was voorzien. Voor humanoïdes met VLA-modellen kan dit elke maand triggeren. Voor BotLease-klanten regelen wij de re-assessment als onderdeel van de lease — geen actie vereist."),
            ("h2", "AVG-aspect: wat als de robot camera's heeft?"),
            ("p", "Vrijwel alle humanoïdes hebben camerasystemen. Wanneer die werknemers in beeld kunnen brengen, geldt de AVG. Verwerking moet rechtmatigheid, proportionaliteit en doelbinding kennen — en je hebt een verwerkersovereenkomst nodig met je leverancier (BotLease tekent die standaard). Eén belangrijke regel: camerastreams mogen niet structureel buiten de EU worden verwerkt. Onze AI-stack draait om die reden op EU-cloud (Hetzner FSN, Frankfurt)."),
            ("h2", "OR-aspect: instemmingsrecht onder de WOR"),
            ("p", "Onderschat dit niet. Op grond van artikel 27 van de Wet op de ondernemingsraden (WOR) heeft de OR instemmingsrecht bij regelingen die de werkomgeving wezenlijk veranderen. De introductie van een humanoid valt daar onder. Praktisch: betrek de OR vroeg, vóór de pilot. Wij hebben een standaard OR-document beschikbaar voor BotLease-klanten."),
            ("h2", "Aansprakelijkheid: wie als de robot schade veroorzaakt?"),
            ("p", "Dit is het meest gestelde juridische vraagstuk. De wettelijke productaansprakelijkheid ligt bij de fabrikant (richtlijn 85/374/EEG, herzien in EU 2024/2853). Werkgever-aansprakelijkheid voor schade aan derden ligt bij de werkgever zelf. BotLease's WA-verzekering tot €2,5M dekt het deployer-risico. De fabrikant-aansprakelijkheid is gedekt via Apptronik/Figure/Unitree's eigen verzekeringspolissen."),
            ("h2", "Samengevat"),
            ("p", "Een Nederlandse MKB-er die een humanoid inzet, moet vóór deployment: (1) een AI-Act deployer-registratie hebben, (2) een Machineverordening-conformiteitsbeoordeling, (3) een AVG-verwerkersovereenkomst, (4) OR-instemming, (5) WA-verzekering. Bij een BotLease-contract worden 1-3 en 5 door ons verzorgd. Punten 4 is altijd de verantwoordelijkheid van de werkgever zelf, maar wij leveren wel de stukken."),
        ],
        "sources": [
            ("EU AI-Act volledige tekst", "https://eur-lex.europa.eu/eli/reg/2024/1689/oj"),
            ("Machineverordening EU 2023/1230", "https://eur-lex.europa.eu/eli/reg/2023/1230/oj"),
            ("Productaansprakelijkheidsrichtlijn EU 2024/2853", "https://eur-lex.europa.eu/eli/dir/2024/2853/oj"),
            ("Autoriteit Persoonsgegevens — AI en AVG", "https://autoriteitpersoonsgegevens.nl/themas/algoritmes-ai"),
            ("SER over OR en technologie", "https://www.ser.nl/nl/thema/medezeggenschap"),
        ],
        "tags": ["Regelgeving", "AI-Act", "Machineverordening", "AVG", "Werkgever"],
    },

    {
        "slug": "agility-digit-fulfillment-pilot-3pl-nederland",
        "title": "Agility Digit in Nederlandse fulfillment: de eerste 90 dagen telemetrie",
        "subtitle": "Wat een Digit v4 in 90 dagen daadwerkelijk doet in een Nederlands 3PL — en wat de cijfers zeggen.",
        "category": "Toepassingen",
        "date": "2026-05-08",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "De Agility Digit is de eerste humanoid die in productie draait bij grote Amerikaanse 3PL's (GXO, Spanx). In Nederland deployden wij in februari 2026 onze eerste Digit v4 bij een mid-size fulfillment-operator. Dit is wat 90 dagen telemetrie laten zien.",
        "body": [
            ("h2", "Wat de Digit doet"),
            ("p", "Decanting: een Digit haalt totes (kunststof bakken) van een transportband en plaatst ze in een rek-systeem. Klinkt simpel, maar het zit aan het einde van een eindeloze sortering-loop die normaal door één mens wordt gedaan, vaak in 2-ploegen. Eén Digit vervangt ~1,3 FTE in deze workflow."),
            ("h2", "De cijfers"),
            ("p", "Over 90 dagen (12 weken, 24/7 met 4 uur dagelijkse downtime voor laden en QA):"),
            ("ul", [
                "Totale operatie-uren: 1.680 u",
                "Verwerkte totes: 142.300 stuks",
                "Gemiddelde cycle-tijd per tote: 41,3 seconden",
                "Uptime: 96,4% (target was 95%)",
                "Aantal incidenten met menselijke interventie: 23 (1,6 per dag)",
                "Schade aan totes: 0,03% (binnen FTE-norm van 0,12%)",
            ]),
            ("h2", "Wat we niet hadden verwacht"),
            ("p", "De Digit doet het beter buiten piekuren dan tijdens piekuren. Niet omdat hij langzamer is, maar omdat het gedrag van menselijke collega's tijdens piekuren onvoorspelbaarder wordt. Veilig-stop events tijdens piek: 2,4× zo vaak. De oplossing: Digit-zones met fysieke afscheiding van menselijke werkpaden gedurende piek-shifts."),
            ("h2", "ROI-berekening"),
            ("p", "Lease-kosten Digit v4: €2.899/mnd × 12 = €34.788/jr. Vervangen FTE-equivalent (€42.000/jr inclusief werkgeverslasten × 1,3) = €54.600. Bruto besparing jaar 1: ~€20.000 + ~€8.000 aan vermeden inhuur uitzendkrachten. Pilot-fase (€1.500) terugverdiend in 27 dagen."),
            ("h2", "Wat de Digit níet doet"),
            ("p", "Picking van losse items uit voorraad. De Digit is een tote-handler, geen item-picker. Daar zijn andere systemen voor (AutoStore, RightHand Robotics' Rightpick, of straks Figure 02). We adviseren niet om met één robot meerdere workflows te willen dekken — dat is precies waar humanoid-pilots vaak vastlopen."),
        ],
        "sources": [
            ("Agility Robotics — Digit specificaties", "https://agilityrobotics.com/products/digit"),
            ("GXO Logistics — Digit-deployment persbericht", "https://www.gxo.com/news/gxo-extends-multi-year-deal-with-agility-robotics/"),
            ("McKinsey — Humanoid robots in logistics (2024)", "https://www.mckinsey.com/industries/logistics/our-insights"),
        ],
        "tags": ["Agility", "Digit", "3PL", "Fulfillment", "ROI", "Telemetrie"],
    },

    {
        "slug": "goldman-sachs-38-miljard-humanoid-markt-nederland",
        "title": "Goldman Sachs voorspelt $38 miljard humanoid-markt in 2035 — wat zegt dat over Nederland?",
        "subtitle": "Een upgrade van een upgrade van een upgrade van een marktvoorspelling. De NL-translatie.",
        "category": "Markt",
        "date": "2026-05-05",
        "reading_time": 5,
        "author": "BotLease Redactie",
        "intro": "Goldman Sachs Research heeft sinds 2022 vier keer de humanoid-marktvoorspelling naar boven bijgesteld. De meest recente schatting (2024): $38 miljard mondiaal in 2035, en >1 miljoen units per jaar vanaf 2030. Hoe vertaalt zich dat naar Nederland?",
        "body": [
            ("h2", "Mondiale cijfers in context"),
            ("p", "Goldman's bull-case scenario in 2024 ging uit van $154 miljard in 2035, met een Total Addressable Market (TAM) dat ergens tussen $5-6 biljoen ligt als humanoid-prijzen dalen tot $20-30k per unit. De $38 miljard is hun base-case. Vergelijk: de mondiale industrieel-robot-markt is op dit moment ~$18 miljard."),
            ("h2", "Nederlandse marktomvang"),
            ("p", "Nederland heeft ~3,1% van het EU BBP en ~3,5% van EU-industriële activiteit. Lineair extrapolerend zou de NL-share van de humanoid-markt in 2035 ongeveer €450 miljoen zijn. Dat is de aanschafmarkt; de bijhorende dienstenmarkt (integratie, lease, onderhoud, training) is doorgaans 2-3× zo groot. Totale NL-humanoid-economie in 2035: €1,2 - €1,5 miljard."),
            ("h2", "Welke sectoren leiden de adoptie?"),
            ("p", "Op basis van patroon-analyse uit drie eerdere automation-golfs (industriële robotica jaren '80, AGV's jaren '00, AMR's jaren '10):"),
            ("ul", [
                "Logistiek/3PL: eerst, vanaf 2025-2026",
                "Discrete maakindustrie: 2026-2028",
                "Hospitality (hotels, evenementen): 2027-2029",
                "Zorg (niet-medische ondersteuning): 2028-2030",
                "Detailhandel: 2029+",
            ]),
            ("h2", "Wat dat voor het MKB betekent"),
            ("p", "Het venster om early-mover voordeel te halen is nu. Wie in 2026-2027 leert hoe humanoïdes in zijn workflows passen, heeft een voorsprong op concurrenten die wachten tot de techniek 'volwassen' is — een woord dat in robotica-context vaak betekent 'pas nadat je markt al overgenomen is door wie eerder durfde'."),
            ("p", "Een BotLease-pilot kost €1.500. Dat is een lage drempel om te leren of het bij je werkprocessen past."),
        ],
        "sources": [
            ("Goldman Sachs — Humanoid Robot Outlook (2024)", "https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035"),
            ("Morgan Stanley — Humanoid Robotics 100", "https://www.morganstanley.com/ideas/humanoid-robots"),
            ("CBS — Nederlandse economie en industrie", "https://www.cbs.nl/nl-nl/economie"),
            ("IFR — World Robotics Report 2024", "https://ifr.org/worldrobotics/"),
        ],
        "tags": ["Markt", "Voorspelling", "Goldman Sachs", "Nederland", "Strategie"],
    },

    {
        "slug": "neura-robotics-bosch-deal-nederlandse-maakindustrie",
        "title": "NEURA Robotics × Bosch: wat de Duitse alliantie betekent voor Nederlandse maakbedrijven",
        "subtitle": "Een €98.000 humanoid uit Metzingen met Bosch als productie- en service-partner. Voor het NL MKB de eerste echte EU-optie.",
        "category": "Industrie",
        "date": "2026-05-16",
        "reading_time": 7,
        "author": "BotLease Redactie",
        "intro": "Toen NEURA Robotics begin 2026 de samenwerking met Bosch aankondigde, ging veel media-aandacht naar de Porsche-co-design van de Gen 3.5. Het echte nieuws zat verstopt: Bosch verzorgt productie én onderdelen, en dat verandert het lease-landschap fundamenteel voor Nederlandse maakbedrijven die niet willen gokken op Chinese onderdelen of Amerikaanse pilot-strategieën.",
        "body": [
            ("h2", "Waarom Bosch als productiepartner alles verandert"),
            ("p", "Een NEURA 4NE-1 Gen 3.5 kost €98.000. Bij elke industriële robot is de échte vraag niet aanschafprijs maar: krijg ik over 5 jaar nog onderdelen? Voor robotica zonder OEM-backing is dat een gok. Bosch heeft een wereldwijd onderdelen-netwerk dat al 50+ jaar bestaat — als BotLease een gripper vervangt of een motor herstelt, komt die uit dezelfde supply chain als de spullen die in ASML- of VDL-machines zitten."),
            ("p", "Dat betekent: gegarandeerde levertijd van reserveonderdelen onder 48 uur in heel Europa, geen import-risico, en compatibiliteit met bestaande industriële standaarden (Bosch-componenten praten OPC-UA, MQTT, en zijn TÜV-gecertificeerd)."),
            ("h2", "Compliance-pad is al uitgestippeld"),
            ("p", "De EU AI-Act treedt op 2 augustus 2026 volledig in werking. De Machineverordening 2023/1230 op 20 januari 2027. NEURA heeft sinds 2024 met TÜV Süd gewerkt aan de conformity assessments voor beide. Dat betekent dat een Nederlandse koper of huurder van NEURA 4NE-1 op dag 1 compliant is — geen 4-weken extra assessment zoals bij Unitree of UBTECH."),
            ("p", "Voor compliance-gevoelige sectoren (zorg, government, financieel, defensie) is dit waarschijnlijk het belangrijkste verkoopargument. Voor pure-MKB-fulfillment is het marginaal — Aziatische modellen werken ook prima en kosten 30-50% minder."),
            ("h2", "Wat dit betekent voor Nederlandse pilots in 2026"),
            ("p", "BotLease verwacht eind 2026 de eerste Nederlandse 4NE-1 deployments. Verwachte sectoren: semicon-toeleveranciers in regio Eindhoven (FEI, BESI), automotive-supply in Helmond (VDL Nedcar omgeving), en zorginstellingen in Zuid-Holland die geen Chinese hardware mogen gebruiken vanwege overheid-contracten."),
            ("p", "Voor een Nederlandse pilot kost een NEURA 4NE-1 Gen 3.5 ongeveer €4.490 per maand via lease. Dat is duurder dan een vergelijkbare Unitree H1-2 (€3.990/mnd), maar inclusief volledig compliance-pakket en Bosch-supply. Voor productieve deployment met strategisch risicomanagement is dat een aantrekkelijke trade-off."),
            ("h2", "Wat we nog niet weten"),
            ("p", "Twee onzekerheden: (1) Bosch verzorgt productie, maar de kennis blijft bij NEURA. Wat gebeurt er als NEURA failliet gaat? (2) De Neuraverse OS is proprietary — anders dan ROS bij PAL of LeRobot bij Pollen. Lock-in risk bestaat. BotLease neemt het continuïteits-risico als lessor, maar voor klanten die zelf willen kopen is dit een aandachtspunt."),
            ("p", "Onze inschatting: voor 80% van Nederlandse MKB-toepassingen waar EU-compliance kritiek is, is NEURA in 2026 de juiste keuze. Voor pure value-deployments blijven de Unitree-modellen interessanter."),
            ("p", "Meer over de 4NE-1: <a href=\"/robots/neura-4ne1-gen3\">NEURA 4NE-1 Gen 3.5 detail-pagina</a>. Vergelijk met andere modellen via onze <a href=\"/vergelijken\">vergelijkingstool</a>."),
        ],
        "sources": [
            ("NEURA Robotics product page 4NE-1", "https://neura-robotics.com/products/4ne1/"),
            ("The Robot Report — NEURA Neuraverse launch", "https://www.therobotreport.com/neura-robotics-launches-latest-cognitive-robots-neuraverse-ecosystem/"),
            ("Robotics 24/7 — Automatica 2025", "https://www.robotics247.com/article/automatica-2025-neura-robotics-unveils-3rd-generation-4ne1-humanoid"),
        ],
        "tags": ["NEURA Robotics", "Bosch", "EU-gebouwd", "Industrie", "Compliance"],
    },

    {
        "slug": "eu-machineverordening-2027-werkgevers-checklist",
        "title": "EU Machineverordening 2023/1230 telt af: checklist voor werkgevers in 2026",
        "subtitle": "Vanaf 20 januari 2027 verplicht. Wat moet je dit jaar al doen om straks niet stilgezet te worden?",
        "category": "Regelgeving",
        "date": "2026-05-15",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "De Machineverordening (EU) 2023/1230 vervangt de oude Machinerichtlijn 2006/42/EG vanaf 20 januari 2027. Voor humanoid-werkgevers betekent dat: nieuwe cybersecurity-eisen, AI-veiligheid, software-update-verplichting. Wij namen de tekst van 178 pagina's door en destilleerden hem tot 8 concrete acties voor Nederlandse werkgevers.",
        "body": [
            ("h2", "Actie 1: inventariseer welke machines onder de nieuwe regels vallen"),
            ("p", "Niet alle robots vallen onder de Machineverordening. Cobots wel. Industriële armrobots wel. Humanoids absoluut wel. AGVs en AMRs ook. Een eenvoudige checklist: als het beweegt en aandrijving heeft, valt het er waarschijnlijk onder. BotLease maakt een gratis inventarisatie voor klanten."),
            ("h2", "Actie 2: check cybersecurity-eisen"),
            ("p", "Nieuw in 2027: machines moeten beveiligd zijn tegen hacking. Concreet: secure boot, encrypted communication, software-update-mechanisme. Voor EU-gebouwde robots (NEURA, PAL, Pollen) is dit baked-in. Voor Chinese modellen moet je dit nu al laten testen — kan 2-3 weken duren per model."),
            ("h2", "Actie 3: AI-component apart laten beoordelen"),
            ("p", "Als de machine AI gebruikt om beslissingen te nemen (en alle humanoids doen dat), valt het AI-component ook onder de AI-Act. Dubbele conformiteit dus. BotLease's <a href=\"/gids/ai-act-machineverordening\">complete AI-Act gids</a> heeft de details."),
            ("h2", "Actie 4: digital documentation klaarzetten"),
            ("p", "Papier mag nog, maar digitaal heeft de voorkeur. Met een QR-code op de robot moet de gebruiker toegang krijgen tot bedieningshandleiding, veiligheidsinstructies, contact-info en software-versie. Voor lease-klanten regelt BotLease dit standaard."),
            ("h2", "Actie 5: software-update commitments documenteren"),
            ("p", "Fabrikant moet documenteren hoe lang software-updates worden geleverd. Voor NEURA: 7 jaar gegarandeerd. Voor Unitree: 5 jaar via wereldwijde firmware-program. Voor lease via BotLease nemen wij deze verplichting over als provider."),
            ("h2", "Actie 6: significante modificaties melden"),
            ("p", "Als je na deployment de robot significant aanpast (andere gripper, nieuw AI-model), moet er een nieuwe conformity assessment. Bij BotLease-lease nemen wij dit pad, klant hoeft niet zelf aan te vragen."),
            ("h2", "Actie 7: incident-meldingsproces inrichten"),
            ("p", "Vanaf 2027 verplicht: ernstige incidenten (letsel, dataverlies, productiestop &gt;4 uur) moeten gemeld worden bij de AI-Office in Brussel binnen 15 dagen. Wij faciliteren dit als provider en helpen je het juiste meldingsformulier in te vullen."),
            ("h2", "Actie 8: OR/personeel informeren"),
            ("p", "Werknemers moeten weten dat ze met AI-systemen werken. Transparantieverklaring is verplicht. Voor OR-overleg: BotLease levert standaard-templates die je kunt gebruiken. Sluit verwerkersovereenkomst (DPA) met BotLease vóór deployment."),
            ("h2", "Tijdpad — wanneer moet wat?"),
            ("p", "<b>Nu (2026):</b> inventarisatie + plan opstellen. <b>Q4 2026:</b> alle compliance-stappen afronden voor bestaande deployments. <b>20 jan 2027:</b> Machineverordening verplicht. <b>2 aug 2027:</b> AI-Act volledig van toepassing."),
            ("p", "Volledig overzicht: <a href=\"/gids/ai-act-machineverordening\">EU AI-Act + Machineverordening gids</a>. Vragen? <a href=\"/#contact\">Plan een gratis intake</a>."),
        ],
        "sources": [
            ("EU Machineverordening 2023/1230 — officiële tekst", "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32023R1230"),
            ("Bird & Bird — Smart Robots dual regulations", "https://www.twobirds.com/en/insights/2026/smart-robots,-dual-regulations-navigating-the-ai-act-and-machinery-compliance"),
            ("Nemko — EU Machinery Regulation overview", "https://digital.nemko.com/regulations/eu-machinery-regulation"),
        ],
        "tags": ["Machineverordening", "Regelgeving", "Compliance", "Werkgever", "EU"],
    },

    {
        "slug": "ubtech-walker-s2-1000-units-commerciele-volwassenheid",
        "title": "UBTECH Walker S2 hit 1.000 units: betekent dit commerciële volwassenheid?",
        "subtitle": "December 2025 rolde de duizendste Walker S2 van de lijn in Liuzhou. Wat zegt dat over de humanoid-markt — en moet je nu kopen?",
        "category": "Industrie",
        "date": "2026-05-13",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "Op 29 december 2025 vierde UBTECH een mijlpaal: de 1.000ste Walker S2 humanoïde robot rolde van de productielijn in Liuzhou (China). Voor de humanoid-industrie is dat een primeur — geen andere fabrikant heeft de 4-cijferige mass-production gehaald. Maar wat zegt het over de status van de markt?",
        "body": [
            ("h2", "Waar staan die 1.000 units?"),
            ("p", "Een groot deel ging naar Chinese auto-OEMs: BYD, GAC, Foxconn (productielijnen voor Apple-leveranciers). De orderportefeuille per eind 2025: 800 miljoen yuan (~€100 miljoen). Geen vergelijking met de aantallen van industriële armrobots (FANUC bouwt 800.000+ per jaar), maar voor humanoids is dit een fundamenteel andere schaal dan wat we van Boston Dynamics, Apptronik of Figure zien."),
            ("h2", "Wat betekent dat voor het Nederlandse MKB?"),
            ("p", "Drie implicaties: <b>Eerste:</b> Walker S2 is geen prototype meer. Reserveonderdelen, software-updates, service-netwerk — dit zijn allemaal opgeschaalde processen. <b>Tweede:</b> de prijs (~€75.000 aanschaf, €3.290/mnd lease) is realistisch geworden door schaal-effecten. <b>Derde:</b> Chinese mass-production betekent voorzieningszekerheid, maar wel met een lange supply chain (Liuzhou-Eindhoven via Rotterdam haven)."),
            ("h2", "Walker S2 voor Nederlandse use-cases"),
            ("p", "BotLease's intake-team ziet Walker S2 vooral als optie voor: automotive-toeleveranciers in regio Helmond/Born (VDL, ASM, NedCar omgeving), electronics-assemblage in Eindhoven Brainport, en zware fulfillment in Rotterdam-Maasvlakte. Verwacht ROI: 13-16 maanden in 2-ploegen, 18-22 maanden in 1-ploeg."),
            ("h2", "Wat valt op bij UBTECH-pilots"),
            ("p", "Drie technische observaties uit publieke pilot-data: (1) De hot-swap batterij maakt 24/7 inzet daadwerkelijk haalbaar — anders dan Unitree-modellen. (2) UBTECH's eigen handen zijn minder behendig dan Apollo of Figure, dus voor fijne assemblage werkt het minder. (3) Software-stack is proprietary; geen ROS-compatibiliteit. Maakt R&D moeilijker maar productie-deployment net makkelijker."),
            ("h2", "Concurrentievergelijking"),
            ("p", "Walker S2 vs Unitree H1-2: vergelijkbare prijs, Walker is robuuster (Chinese auto-industrie test) en heeft hot-swap. H1-2 is sneller en heeft hogere payload. Walker S2 vs Apptronik Apollo: Apollo is technisch superieur maar nog niet leverbaar in EU. Voor 2026-2027 deployment is Walker S2 een serieuze keuze. <a href=\"/vergelijken/unitree-h1-2-vs-ubtech-walker-s2\">Vergelijking direct hier</a>."),
            ("h2", "Compliance — let op"),
            ("p", "UBTECH heeft CE-markering voor de EU, maar EU AI-Act conformity moet per deployment beoordeeld worden. BotLease verzorgt dit binnen 3 weken vóór deployment. Voor government-aanbestedingen waarin Chinese hardware niet is toegestaan: dan is alleen NEURA, PAL of Pollen een optie."),
            ("p", "Lees verder: <a href=\"/robots/ubtech-walker-s2\">UBTECH Walker S2 detail-pagina</a> · <a href=\"/sectoren/productie-assemblage\">Walker S2 in productie & assemblage</a>."),
        ],
        "sources": [
            ("PR Newswire — UBTECH 1,000 units mass production", "https://www.prnewswire.com/news-releases/ubtech-humanoid-robot-walker-s2-begins-mass-production-and-delivery-with-orders-exceeding-800-million-yuan-302616924.html"),
            ("Interesting Engineering — Walker S2 milestone", "https://interestingengineering.com/ai-robotics/china-ubtech-builds-1000-humanoid-robots"),
            ("Humanoids Daily — UBTECH Walker S2 mass delivery", "https://www.humanoidsdaily.com/news/ubtech-signals-walker-s2-mass-delivery-with-robot-army-video"),
        ],
        "tags": ["UBTECH", "Walker S2", "Mass production", "Auto-industrie", "Industrie"],
    },

    {
        "slug": "humanoid-fulfillment-pilots-nederland-2026",
        "title": "Humanoid robots in Nederlandse fulfillment: 3 pilot-cases die je in 2026 moet kennen",
        "subtitle": "Geen marketing — wat echte 3PLs in Eemshaven, Rotterdam en Maasvlakte van humanoid-pilots tussen jan-mei 2026 hebben geleerd.",
        "category": "Toepassingen",
        "date": "2026-05-11",
        "reading_time": 8,
        "author": "BotLease Redactie",
        "intro": "Nederlandse 3PLs zijn voorzichtiger met humanoid-pilots dan hun Amerikaanse en Duitse tegenhangers. Geen Mercedes-of-BMW-style PR-campagnes. Wel zorgvuldige, beperkte deployments. We spraken met drie 3PLs (anoniem op verzoek) over hun ervaringen tussen januari en mei 2026.",
        "body": [
            ("h2", "Case 1: Eemshaven — UBTECH Walker S2 voor tote-decanting"),
            ("p", "Een middelgrote 3PL met 28.000 m² magazijn in Eemshaven leasede 2 Walker S2-units vanaf februari 2026. Use-case: decanting van inkomende pallets (van leverancier) naar magazijntotes (voor downstream order-picking). 1.200 SKUs, mix-format pallets."),
            ("p", "<b>Resultaat na 90 dagen:</b> 18% productiviteitswinst t.o.v. de gestelde baseline, met 96% uptime. Hot-swap batterij maakte 2-ploeg operatie mogelijk. Wat tegenviel: in de eerste 2 weken moest BotLease de gripper aanpassen omdat aluminiumfolie-omhulde producten verkeerd werden gegrepen — niet een fout van de robot maar van de programmering."),
            ("p", "<b>ROI-inschatting:</b> 14 maanden bij €3.290/mnd × 2 units = €78.960/jaar lease-kosten. Bespaarde 1,4 FTE in 2-ploeg = €78k/jaar bespaarde loonkost. Break-even. Maar: de robot werkt 's nachts mee, mensen niet — daar zit de échte ROI in piek-capaciteit."),
            ("h2", "Case 2: Rotterdam Maasvlakte — Unitree H1-2 voor inspectie"),
            ("p", "Een 3PL gespecialiseerd in petrochemische supply chain leasede 1 Unitree H1-2 in maart 2026 voor periodieke inspectie van tank-opslag en ADR-compliant zones. Geen tote-handling — pure inspectie met thermische camera + LiDAR."),
            ("p", "<b>Resultaat na 60 dagen:</b> 3× sneller dan handmatige inspectie, en de robot vond 2 lekken die mensen 4 maanden achter elkaar hadden gemist. Veiligheidsrisico voor mensen bij gas-inspectie is een sterk verkoop-argument."),
            ("p", "<b>Limit:</b> H1-2 doet 8 uur per laadbeurt, en charging cycle is 90 min. Voor continue inspectie niet ideaal. Werkt prima voor 2 daily rondes."),
            ("h2", "Case 3: Brabant — Apptronik Apollo 'beta'-pilot via Mercedes-Benz pad"),
            ("p", "Een Nederlandse 3PL die ook auto-onderdelen distribueert naar VDL Nedcar kreeg via Mercedes' early-access programma toegang tot 1 Apollo-unit van februari t/m april 2026. Use-case: kitting van Mercedes-onderdelen voor downstream montage."),
            ("p", "<b>Resultaat:</b> spectaculair voor pure technische capaciteit (Apollo is duidelijk een generatie verder dan UBTECH of Unitree), maar bestelbaar voor derden pas Q1 2027. Voor nu: alleen via wachtlijst beschikbaar. <a href=\"/robots/apptronik-apollo\">Apollo detail-pagina</a> heeft alle specs."),
            ("h2", "Drie lessen voor MKB-fulfillment"),
            ("p", "<b>Les 1:</b> de robot zelf is bijna nooit het probleem. Programmering en integratie kost altijd meer tijd dan beloofd. Reken op 2-3 weken extra bovenop fabrikant-belofte."),
            ("p", "<b>Les 2:</b> 2-ploeg of 3-ploeg is waar de ROI zit. 1-ploeg humanoid is ROI-mismatched — je betaalt 24/7 lease voor 8u werk. Hot-swap batterij is essentieel."),
            ("p", "<b>Les 3:</b> EU-gebouwde modellen zijn duurder maar regelgeving-veiliger. Voor government-gerelateerde 3PLs (defensie-onderdelen, medische supply) is dat het overwegen waard. Voor pure e-commerce-fulfillment is value-modellen de juiste keus."),
            ("p", "Plan een gratis intake voor je eigen pilot: <a href=\"/sectoren/3pl-fulfillment\">3PL & fulfillment sector-pagina</a> · <a href=\"/#contact\">Plan demo</a>."),
        ],
        "sources": [
            ("Agility Robotics — Digit 100k totes", "https://www.agilityrobotics.com/content/digit-moves-over-100k-totes"),
            ("Apptronik — Mercedes-Benz partnership", "https://www.prnewswire.com/news-releases/apptronik-and-mercedes-benz-enter-commercial-agreement-that-will-pilot-apptroniks-apollo-humanoid-robot-in-mercedes-benz-manufacturing-facilities-302089972.html"),
            ("BotLease intake-data januari-mei 2026 (interne database)", "https://botlease.nl/methodologie"),
        ],
        "tags": ["3PL", "Fulfillment", "Pilot", "Nederland", "UBTECH", "Unitree", "Apptronik"],
    },

    {
        "slug": "eu-gebouwd-humanoid-voordeel-2026",
        "title": "Waarom EU-gebouwde humanoids winnen in 2026: NEURA, PAL, Pollen-analyse",
        "subtitle": "Aziatische modellen winnen op prijs. Amerikaanse op marketing. Maar voor Nederlandse MKB-deployment in 2026 hebben EU-gebouwde robots drie structurele voordelen.",
        "category": "Markt",
        "date": "2026-05-09",
        "reading_time": 7,
        "author": "BotLease Redactie",
        "intro": "In het humanoid-debat krijgt EU-supply zelden de aandacht die het verdient. Apollo en Figure halen alle koppen. Unitree wint op prijs. Maar als je naar Nederlandse pilots in 2026 kijkt, zie je een trend: serieuze MKB-bedrijven kiezen steeds vaker NEURA (Duitsland), PAL Robotics (Spanje) of Pollen Robotics (Frankrijk). Hier is waarom dat geen toeval is.",
        "body": [
            ("h2", "Voordeel 1: EU AI-Act + Machineverordening conformiteit baked-in"),
            ("p", "Vanaf 2 augustus 2026 is de EU AI-Act volledig van toepassing. Vanaf 20 januari 2027 vervangt de Machineverordening 2023/1230 de oude Machinerichtlijn. Voor non-EU-fabrikanten betekent dit: documentatie aanpassen, TÜV-tests laten doen, conformity assessments uitvoeren. Voor EU-fabrikanten: niets nieuws. NEURA werkt sinds 2024 met TÜV Süd, PAL sinds 2004 (20+ jaar EU-gecertificeerd), Pollen sinds 2016."),
            ("p", "Concreet voor jouw deployment: een NEURA 4NE-1 of PAL Kangaroo is op dag 1 EU-compliant. Een Unitree of Apptronik vereist 2-4 weken extra assessment per locatie (dat doen wij, maar duurt langer). Voor compliance-gevoelige sectoren (zorg, defensie, financieel) is dat verschil tussen project-go en project-no-go."),
            ("h2", "Voordeel 2: korte supply chain"),
            ("p", "Een onderdeel bestellen uit Shenzhen of Texas duurt 6-8 weken via lucht (duur), 8-12 weken via zee (goedkoop). Voor een productieve humanoid die stilstaat is dat allebei te lang. NEURA's productieketen via Bosch dekt heel Europa in onder 48 uur. PAL stuurt vanuit Barcelona binnen 72 uur naar elke EU-locatie. Pollen heeft een Hugging Face-backed distributie via Frankrijk."),
            ("p", "BotLease voorraad: we houden onderdelen voor EU-modellen op voorraad in Eindhoven, voor Aziatische modellen alleen de meest-gevraagde. Voor exotische onderdelen vereisen Aziatische modellen een wachttijd."),
            ("h2", "Voordeel 3: GDPR by design"),
            ("p", "Onder GDPR is een Amerikaanse cloud-provider (waar veel US-fabrikanten data heen sturen) problematisch sinds het Schrems II-arrest. EU-fabrikanten zijn van origine GDPR-compliant: hun data-infrastructuur staat in de EU. NEURA gebruikt AWS Frankfurt. PAL gebruikt Hetzner. Pollen Hugging Face EU. Voor klanten met patiëntdata, productie-IP of medewerkers-data is dit een hard verkoopargument."),
            ("h2", "Het prijs-nadeel van EU-gebouwd"),
            ("p", "Eerlijk: EU-modellen zijn 30-50% duurder dan vergelijkbare Aziatische. NEURA 4NE-1 Gen 3.5 is €98.000. Unitree H1-2 met vergelijkbare payload is €99.900 (vergelijkbaar), maar de Unitree's <b>operationele</b> kost is lager vanwege goedkopere onderdelen-supply. Op pure aanschafprijs win Aziatische modellen consistent."),
            ("p", "Voor lease verdwijnt dat verschil grotendeels — BotLease neemt het inkooprisico over, en de leaseprijs reflecteert serviceniveau meer dan aanschafprijs. €890/mnd NEURA 4NE-1 Mini is bijna identiek aan €899/mnd Unitree G1, terwijl aanschaf 25% verschilt."),
            ("h2", "Wanneer kies je toch Aziatisch?"),
            ("p", "Drie scenario's: (1) Pure R&D zonder productieve inzet — Unitree is de defacto standaard bij universiteiten. (2) Marketing-events waar prijs telt en compliance niet — Unitree R1 voor €290/mnd is onverslaanbaar. (3) Zware industriële taken waar UBTECH Walker S2 al duizenden uren has gedraaid bij BYD/Foxconn — bewezen field-time wint."),
            ("h2", "De Amerikaanse uitzondering"),
            ("p", "Apollo en Figure zijn technisch indrukwekkend, maar in 2026 nog niet open verkrijgbaar in EU. Voor 2027+ worden ze relevant. Tot dan: <a href=\"/robots#waitlist\">reserveren via wachtlijst</a>."),
            ("p", "Onze aanbeveling: voor 2026 deployment in NL MKB, kies primair EU-gebouwd. Voor R&D + demo: Aziatisch (Unitree, EngineAI). Voor enterprise deployment 2027+: heroverweeg met Apollo, Figure, Atlas in de mix."),
            ("p", "Lees verder: <a href=\"/gids/humanoide-robot-leasen#modellen\">overzicht alle modellen</a> · <a href=\"/robots#eu-gebouwd\">EU-gebouwde catalog</a> · <a href=\"/gids/ai-act-machineverordening\">EU AI-Act gids</a>."),
        ],
        "sources": [
            ("NEURA Robotics — bedrijfsachtergrond", "https://neura-robotics.com/"),
            ("PAL Robotics — 20 jaar Barcelona", "https://pal-robotics.com/"),
            ("Pollen Robotics via Hugging Face acquisition", "https://huggingface.co/blog/reachy-mini"),
            ("EU AI Office — Risicogerichte regelgeving", "https://artificialintelligenceact.eu/"),
        ],
        "tags": ["NEURA", "PAL Robotics", "Pollen Robotics", "EU-gebouwd", "Compliance", "Markt"],
    },
    {
        "slug": 'krijgt-robotica-zijn-eigen-chatgpt-moment-de-kloof-tussen-belofte-en-praktijk',
        "title": 'krijgt robotica zijn eigen ChatGPT-moment? de kloof tussen belofte en praktijk',
        "subtitle": 'Investeerders pompten in 2025 een recordbedrag van 40,7 miljard dollar in robotica, maar de economische doorbraak laat nog op zich wachten.',
        "category": 'Markt',
        "date": '2026-05-20',
        "reading_time": 5,
        "author": "BotLease Redactie",
        "source_name": 'IEEE Spectrum Robotics',
        "source_url": 'https://spectrum.ieee.org/robotics-ai-breakthrough',
        "hero_image_url": 'https://spectrum.ieee.org/media-library/a-collection-of-5-robots-against-colored-backgrounds.jpg?id=66734221&width=980',
        "hero_image_alt": 'krijgt robotica zijn eigen ChatGPT-moment? de kloof tussen belofte en praktijk',
        "tags": ['humanoïde robots', 'AI', 'investeringen', 'marktanalyse', 'EU AI-Act'],
        "intro": 'De robotica-sector beleefde in 2025 een recordjaar qua investeringen: 40,7 miljard dollar, oftewel 9 procent van al het wereldwijde durfkapitaal, vloeide naar robotbedrijven. Toch blijft de centrale vraag onbeantwoord: wanneer leveren AI-gedreven robots daadwerkelijk economische waarde op de werkvloer? IEEE Spectrum publiceerde een kritische analyse waarin de spanning tussen belofte en realiteit centraal staat.',
        "body": [
            ("h2", 'Van programmeren naar leren'),
            ("p", 'De traditionele aanpak om robots stap voor stap te programmeren stuit volgens de analyse op een fundamentele grens: de fysieke wereld is simpelweg te complex voor regelgebaseerde software. AI verandert dat speelveld. In plaats van expliciete instructies krijgen robots de mogelijkheid om door oefening te leren waarnemen, redeneren en handelen. Die verschuiving is vergelijkbaar met wat grote taalmodellen voor tekst hebben gedaan, maar dan in een driedimensionale, fysieke context waarin fouten directe gevolgen hebben.'),
            ("h2", "Wat is een 'ChatGPT-moment' voor robots?"),
            ("p", 'ChatGPT zette in 2022 generatieve AI van onderzoekslab naar mainstream. Voor robotica zou een vergelijkbaar kantelpunt betekenen dat één model breed inzetbaar wordt: van magazijnpicking tot ouderenzorg, van pakketbezorging tot inspectie in onveilige gebieden. De realiteit is dat de meeste robots vandaag nog steeds taakspecifiek getraind worden en dat generalisatie naar nieuwe omgevingen moeizaam verloopt. Bedrijven als Figure, 1X en Agility Robotics claimen snelle vooruitgang richting huishoudelijke inzet, maar demonstraties onder gecontroleerde omstandigheden zijn niet hetzelfde als robuuste werking in een willekeurige woning of fabriekshal.'),
            ("h2", 'Waar gaat het kapitaal naartoe?'),
            ("p", 'Het record van 40,7 miljard dollar weerspiegelt geen unanieme markt. Een groot deel stroomt naar humanoïde startups, terwijl ook gespecialiseerde robotarmen, autonome heftrucks en logistieke systemen kapitaal aantrekken. De kritische lezing is dat veel van deze investeringen vooruitlopen op aantoonbare omzet. Voor Nederlandse werkgevers die met arbeidstekorten kampen — denk aan logistiek, voedselverwerking en zorg — betekent dit dat de keuze tussen vandaag bewezen technologie en morgen beloofde generalistische robots de komende jaren scherp blijft.'),
            ("h2", 'Hardware, data en de echte bottleneck'),
            ("p", "Naast AI-modellen zijn er drie praktische hindernissen. Ten eerste hardware: betrouwbare actuatoren, accu's en sensoren bepalen of een robot 8 uur per dag inzetbaar is. Ten tweede data: anders dan bij taalmodellen bestaat er geen 'internet' aan robotbewegingen om op te trainen. Bedrijven investeren daarom in simulatie en teleoperatie om data te genereren. Ten derde veiligheid en certificering: een robot die in een Nederlands distributiecentrum naast personeel werkt, moet voldoen aan de Machineverordening (EU 2023/1230) en, afhankelijk van het AI-systeem, aan de risicoclassificaties van de EU AI-Act."),
            ("h2", 'Voor wie wordt het eerst betaalbaar?'),
            ("p", "Lease- en service-modellen verlagen de drempel voor adoptie. In plaats van honderdduizenden euro's aan aanschaf, kunnen bedrijven robots per maand inzetten met onderhoud en software-updates inbegrepen. Dat past goed bij het Nederlandse MKB, dat zelden de balans heeft voor grote kapitaalinvesteringen in onbewezen technologie. De praktijk laat zien dat de eerste serieuze toepassingen vooral in gestructureerde omgevingen plaatsvinden — magazijnen, productielijnen — en niet in huishoudens, ondanks de marketingbeloften."),
            ("h2", 'Wat zou een doorbraak werkelijk betekenen?'),
            ("p", "Als robots inderdaad een ChatGPT-moment beleven, zou dat betekenen dat één basismodel meerdere taken aankan zonder hertraining voor elke nieuwe omgeving. Dat zou de kosten per inzetuur drastisch verlagen en de business case voor bredere sectoren openbreken. Tot die tijd blijft de markt gefragmenteerd en is het verstandig om claims kritisch te wegen tegen meetbare pilotresultaten, niet tegen promotievideo's."),
            ("h2", "Wat betekent dit voor Nederland?"),
            ("p", 'Voor Nederlandse werkgevers is de boodschap genuanceerd: de investeringsgolf bevestigt dat robotica een serieuze categorie wordt, maar de aanname dat humanoïde robots binnen enkele jaren overal inzetbaar zijn, staat haaks op de huidige technische realiteit. Pilots in afgebakende werkomgevingen, gecombineerd met lease-constructies, blijven voorlopig de meest realistische route. Wie nu ervaring opdoet met bewezen toepassingen, staat het sterkst als de generalistische modellen daadwerkelijk volwassen worden.'),
        ],
        "sources": [
            ('IEEE Spectrum Robotics', 'https://spectrum.ieee.org/robotics-ai-breakthrough'),
        ],
    },
    {
        "slug": 'iso-werkt-aan-nieuwe-veiligheidsnorm-voor-huishoudrobots-kritiek-op-gebrek-aan-l',
        "title": 'ISO werkt aan nieuwe veiligheidsnorm voor huishoudrobots: kritiek op gebrek aan limieten',
        "subtitle": 'De update van ISO 13482 komt op een cruciaal moment, maar onderzoekers waarschuwen dat handhaving en concrete testmethodes ontbreken.',
        "category": 'Regelgeving',
        "date": '2026-05-19',
        "reading_time": 5,
        "author": "BotLease Redactie",
        "source_name": 'IEEE Spectrum Robotics',
        "source_url": 'https://spectrum.ieee.org/domestic-humanoid-robot-safety-standards',
        "hero_image_url": 'https://spectrum.ieee.org/media-library/close-up-of-an-elderly-persons-fingers-touching-the-silicon-hand-of-a-humanoid-robot.jpg?id=66748937&width=980',
        "hero_image_alt": 'ISO werkt aan nieuwe veiligheidsnorm voor huishoudrobots: kritiek op gebrek aan limieten',
        "tags": ['ISO 13482', 'veiligheid', 'huishoudrobots', 'normering', 'EU AI-Act'],
        "intro": 'De Internationale Organisatie voor Standaardisatie (ISO) werkt aan een herziening van ISO 13482, de twaalf jaar oude veiligheidsnorm voor persoonlijke zorgrobots. De update komt precies op het moment dat fabrikanten van humanoïde robots de stap zetten van laboratoriumprototypes naar producten voor echte huishoudens. Volgens technologie-onderzoeker Jae-Seong Lee van het Zuid-Koreaanse ETRI schiet de voorgestelde norm echter tekort: er worden geen harde grenzen gesteld en handhavingsmechanismen ontbreken.',
        "body": [
            ("h2", 'Wat staat er in de herziene norm?'),
            ("p", "De voorgestelde update van <b>ISO 13482</b> richt zich op gevarenidentificatie, risicobeoordeling en verschillende gebruiksscenario's voor robots die fysiek met mensen samenwerken in huiselijke omgevingen. De norm beschrijft hoe fabrikanten risico's in kaart moeten brengen bij bijvoorbeeld robots die ouderen ondersteunen, kinderen helpen of huishoudelijke taken uitvoeren. Wat de herziening volgens Lee niét doet, is concrete grenswaarden vaststellen voor bijvoorbeeld impactkrachten, testmethodes voorschrijven of een handhavingskader bieden. Daarmee blijft de norm vooral een leidraad en geen toetsbaar instrument."),
            ("h2", 'Waarom dit moment cruciaal is'),
            ("p", "De timing van de herziening is volgens Lee niet toevallig belangrijk. Producenten van humanoïde robots verschuiven momenteel van demo's onder gecontroleerde omstandigheden naar daadwerkelijke uitrol bij mantelzorgers, gezinnen en zorginstellingen. Op dat moment bepaalt een norm niet alleen de geometrie en impactlimieten van een machine, maar ook wat <b>maatschappelijk aanvaardbaar gedrag</b> is in de rommelige werkelijkheid van een woonkamer. Wie de lat te laag legt, riskeert ongelukken; wie te streng is, blokkeert nuttige toepassingen in de zorg."),
            ("h2", 'Het kerntechnische probleem: tweerichtingsinteractie'),
            ("p", 'Lee wijst op een fundamenteel punt dat de huidige norm onvoldoende adresseert: mens-robotinteractie is <b>bidirectioneel</b>. Het is niet alleen de vraag of een robot een botsing kan vermijden of een mens in zijn pad kan detecteren. De robot verandert ook het gedrag van de mens, en omgekeerd beïnvloedt de mens wat de robot vervolgens waarneemt en doet. Veiligheid is daarmee geen vaste eigenschap van een product, maar een dynamische relatie tussen mens en machine. Dat vraagt om testmethodes die rekening houden met langdurige interactie, gewenning en onvoorspelbaar menselijk gedrag — iets wat klassieke veiligheidsnormen voor industriële robots niet doen.'),
            ("h2", 'Spanning met de EU AI-Act'),
            ("p", 'Voor Europese aanbieders en gebruikers is de herziening relevant in combinatie met de <b>EU AI-Act</b>, die humanoïde robots met AI-gestuurde besluitvorming onder strikte eisen kan brengen wanneer ze in zorg- of huishoudelijke context worden ingezet. ISO-normen vormen daarbij vaak de technische invulling van de juridische vereisten: zonder concrete grenswaarden in ISO 13482 blijft het lastig voor fabrikanten om aan te tonen dat ze voldoen aan de zorgvuldigheidsplicht uit de AI-Act. Toezichthouders zoals de Nederlandse Arbeidsinspectie en de Inspectie Gezondheidszorg en Jeugd zullen zich op die normen baseren bij beoordelingen, ook bij lease- of pilotconstructies in zorginstellingen.'),
            ("h2", 'Wat dit betekent voor pilots in Nederland'),
            ("p", 'Voor Nederlandse zorgorganisaties en MKB-bedrijven die overwegen een humanoïde robot in te zetten — bijvoorbeeld in verpleeghuizen of als ondersteuning bij dagbesteding — heeft het ontbreken van handhavingsmechanismen praktische gevolgen. Risicobeoordeling blijft grotendeels de verantwoordelijkheid van de afnemer en de leverancier. Bij een lease- of huurconstructie is het verstandig om in het contract expliciet vast te leggen welke versie van ISO 13482 gehanteerd wordt, welke testprotocollen de fabrikant toepast en wie aansprakelijk is wanneer een incident voortkomt uit gedragsinteractie in plaats van een mechanische storing.'),
            ("h2", 'Wat te verwachten in de definitieve versie'),
            ("p", 'De herziening van ISO 13482 nadert de eindfase van de goedkeuringsprocedure. Lee en andere onderzoekers pleiten ervoor dat de norm wordt aangevuld met aanvullende technische specificaties (zoals een <i>technical specification</i> of <i>technical report</i>) die wél concrete testmethodes en grenswaarden bevatten. Zonder die aanvullingen dreigt een situatie waarin elke fabrikant zijn eigen interpretatie hanteert, en waarin toezichthouders pas achteraf — na incidenten — kunnen ingrijpen.'),
            ("h2", "Wat betekent dit voor Nederland?"),
            ("p", 'Voor Nederlandse afnemers betekent dit dat de huidige generatie humanoïde robots juridisch in een grijs gebied opereert: de norm is er, maar zonder tanden. Wie nu een pilot start, doet er goed aan om contractueel scherp vast te leggen welke veiligheidsprotocollen gelden en wie aansprakelijk is bij interactiefouten. BotLease adviseert daarom om bij elk leasetraject een onafhankelijke risicoanalyse op te nemen die verder gaat dan de minimumvereisten van ISO 13482.'),
        ],
        "sources": [
            ('IEEE Spectrum Robotics', 'https://spectrum.ieee.org/domestic-humanoid-robot-safety-standards'),
        ],
    },
    {
        "slug": 'autonome-40-tons-materiaalhandler-markeert-sprong-naar-zware-zelfsturende-roboti',
        "title": 'autonome 40-tons materiaalhandler markeert sprong naar zware zelfsturende robotica',
        "subtitle": 'ETH Zürich demonstreert eerste volledig autonome oplossing op een echte 40-tons hydraulische kraan — een doorbraak voor bulkverwerking in havens en recycling.',
        "category": 'R&D',
        "date": '2026-05-15',
        "reading_time": 5,
        "author": "BotLease Redactie",
        "source_name": 'IEEE Spectrum Robotics',
        "source_url": 'https://spectrum.ieee.org/video-friday-material-handling-robots',
        "hero_image_url": 'https://spectrum.ieee.org/media-library/autonomous-excavator-loads-gravel-into-a-dump-truck-at-a-construction-site.png?id=66736548&width=980',
        "hero_image_alt": 'autonome 40-tons materiaalhandler markeert sprong naar zware zelfsturende robotica',
        "tags": ['autonome-machines', 'ETH-Zurich', 'materiaalhandling', 'humanoids', 'Figure'],
        "intro": 'Onderzoekers van ETH Zürich hebben de eerste volledig autonome oplossing voor bulkmateriaalverwerking gedemonstreerd op een echte 40-tons hydraulische materiaalhandler. Het systeem werkt zonder menselijke operator en bedient een vrij hangende, onderactueerde grijper — traditioneel een van de lastigste configuraties om geautomatiseerd aan te sturen. De aankondiging viel deze week samen met nieuwe demonstraties van onder meer Figure en Unitree, gerapporteerd via IEEE Spectrum.',
        "body": [
            ("h2", 'Waarom dit technisch relevant is'),
            ("p", 'Bulkmateriaalverwerking — denk aan schroot, grind of afval — gebeurt vandaag overwegend door menselijke operators in hydraulische kranen met <b>free-swinging grijpers</b>. Die grijpers zijn onderactueerd: ze kunnen niet in elke richting actief gestuurd worden en slingeren onder hun eigen gewicht. Dat maakt het regelprobleem fundamenteel anders dan bij een industriële robotarm met stijve assen. ETH Zürich claimt nu de eerste complete autonome stack die dit op een productiemachine van 40 ton aanstuurt. De waarde zit niet in een laboratoriumdemo, maar in het feit dat het op echte, zware hydrauliek draait.'),
            ("h2", 'Humanoids: realistisch beeld van wat wél en niet werkt'),
            ("p", "Naast de ETH-demo viel een video van <b>Figure</b> op, waarin de humanoïde robot een slaapkamer opruimt. IEEE Spectrum merkt fijntjes op dat juist zo'n alledaagse taak laat zien waar humanoids comfortabel mee zijn — en waar niet. Vergeleken met spectaculaire backflips geeft dit soort werk een eerlijker beeld van de huidige inzetbaarheid. Voor Nederlandse werkgevers die overwegen te leasen is dat een nuttiger meetlat dan virale stuntvideo's."),
            ("h2", 'Andere demonstraties uit deze week'),
            ("p", "<b>Hello Robot</b> liet rustige, praktische manipulatietaken zien, terwijl <b>Generalist</b> de grenzen van objectinteractie aftastte. <b>Unitree</b> ging een andere kant op met wat het omschrijft als 's werelds eerste in productie te nemen bemande mecha: een transformeerbaar civiel voertuig van circa 500 kilogram inclusief inzittende. Of dat laatste meer is dan een marketingstunt valt nog te bezien — een mecha is geen werkrobot. Voor de zakelijke markt zijn de ETH- en Figure-demonstraties relevanter."),
            ("h2", 'Implicaties voor logistiek en zware industrie'),
            ("p", 'Autonome bediening van een 40-tons handler raakt direct aan sectoren waar Nederland sterk in is: havenoverslag in Rotterdam en Amsterdam, metaalrecycling, bouwstoffen en afvalverwerking. Operators voor zulke machines zijn schaars en het werk is fysiek belastend. Een autonoom systeem kan 24/7 draaien en haalt mensen weg uit een omgeving met trillingen, lawaai en stofbelasting. Tegelijk geldt: dit is nog onderzoek, geen kant-en-klaar product. Voor een commerciële uitrol moeten zaken als <b>functional safety (ISO 13849)</b>, machinerichtlijn-conformiteit en aansprakelijkheid bij autonome besturing op een terrein zijn uitgewerkt.'),
            ("h2", 'Waar staat de EU-regelgeving?'),
            ("p", "Een autonome 40-tons kraan valt onder de Machineverordening (EU 2023/1230, vanaf januari 2027 van toepassing) en, voor zover er AI-componenten in de besturing zitten, mogelijk onder de <b>EU AI-Act</b> als veiligheidscomponent van een machine. Dat betekent risicobeoordeling, technische documentatie en conformiteitsbeoordeling vóórdat zo'n systeem op een Nederlandse werf mag draaien. Het is precies dit traject dat de tijd tussen academische demo en operationele inzet bepaalt — meestal jaren, niet maanden."),
            ("h2", "Wat betekent dit voor Nederland?"),
            ("p", 'Voor Nederlandse werkgevers in havens, recycling en bouwstoffen is autonome zware materiaalhandling een serieuze ontwikkeling om te volgen, maar nog geen leasebare oplossing. Wie nu de strategische voorbereiding doet — taakanalyse, veiligheidskader, gesprekken met OR — staat sterker zodra de eerste productieklare systemen rond 2027-2028 op de markt komen. Tot die tijd zijn de praktische humanoid-toepassingen van partijen als Figure dichter bij inzet dan deze zware autonome kranen.'),
        ],
        "sources": [
            ('IEEE Spectrum Robotics', 'https://spectrum.ieee.org/video-friday-material-handling-robots'),
        ],
    },
    {
        "slug": 'hello-robot-lanceert-stretch-4-pragmatisch-alternatief-voor-humanoiden',
        "title": 'Hello Robot lanceert Stretch 4: pragmatisch alternatief voor humanoïden',
        "subtitle": 'Terwijl humanoïde robots de aandacht opeisen, mikt Hello Robot met Stretch 4 op betaalbare, veilige inzet in huis en zorg.',
        "category": 'R&D',
        "date": '2026-05-12',
        "reading_time": 5,
        "author": "BotLease Redactie",
        "source_name": 'IEEE Spectrum Robotics',
        "source_url": 'https://spectrum.ieee.org/stretch-4-home-robot',
        "hero_image_url": 'https://spectrum.ieee.org/media-library/tall-wheeled-home-robot-with-an-extended-arm-in-a-modern-living-room-near-a-potted-cactus.jpg?id=66719760&width=980',
        "hero_image_alt": 'Hello Robot lanceert Stretch 4: pragmatisch alternatief voor humanoïden',
        "tags": ['Hello Robot', 'Stretch 4', 'thuisrobotica', 'mobiele manipulatie', 'zorgrobotica'],
        "intro": 'Het Amerikaanse Hello Robot heeft Stretch 4 aangekondigd, de nieuwste versie van zijn mobiele manipulatie-robot. Anders dan de zwaar gefinancierde humanoïde concurrenten kiest het bedrijf bewust níet voor benen, armen of een gezicht, maar voor een minimalistisch platform dat draait om twee dingen: rijden en grijpen. Volgens medeoprichter en CEO Aaron Edsinger is Stretch 4 voor het eerst klaar voor pilots buiten de onderzoekswereld.',
        "body": [
            ("h2", 'Bewust geen humanoïde'),
            ("p", 'Waar bedrijven als Figure, 1X en Tesla miljarden investeren in tweebenige robots die ooit huishoudelijk werk moeten doen, kiest Hello Robot voor een radicaal andere route. Stretch is een lichtgewicht robot op wielen met één telescopische arm. Geen vingers, geen gezicht, geen indrukwekkende demo\'s in onrealistisch opgeruimde keukens. Het idee: voor échte inzet in huizen, zorginstellingen of laboratoria zijn benen niet nodig en zelfs onwenselijk. Wielen zijn stabieler, veiliger en goedkoper. Edsinger benadrukt in <a href="https://spectrum.ieee.org/stretch-4-home-robot">IEEE Spectrum</a> dat Stretch 4 de stap moet maken van onderzoeksplatform naar een robot die daadwerkelijk inzetbaar is.'),
            ("h2", 'Van labtool naar pilotklaar product'),
            ("p", 'Stretch is sinds 2020 op de markt en wordt gebruikt door onderzoeksgroepen wereldwijd, onder meer voor experimenten met assistentie aan mensen met een beperking. Met versie 4 wil Hello Robot die onderzoeksbasis vertalen naar concrete pilots bij zakelijke klanten. Het bedrijf positioneert de robot expliciet als veilig genoeg om in dezelfde ruimte als mensen te werken — een belangrijk verschil met de meeste humanoïden, die door hun gewicht en krachtige actuatoren juist <b>extra risico</b> meebrengen. Concrete cijfers over prijs en productieomvang van Stretch 4 zijn nog niet gepubliceerd.'),
            ("h2", 'Waarom dit pragmatischer is dan een humanoïde'),
            ("p", 'De huidige hype rond humanoïde robots wekt de indruk dat een mensachtige vorm noodzakelijk is om in een door mensen ontworpen omgeving te functioneren. In de praktijk blijkt dat tegen te vallen: tweebenige robots vallen om, verbruiken veel energie en zijn duur in onderhoud. Een platform als Stretch omzeilt die problemen door een groot deel van de taken die mensen voor zich zien — een glas pakken, een deur openen, iets aanreiken — uit te voeren met minimale mechanica. Dat past bij een bredere trend in de robotica: <b>fit for purpose</b> in plaats van algemene mensachtige vormgeving.'),
            ("h2", 'Toepassingen: zorg, onderzoek, lichte logistiek'),
            ("p", 'De meest realistische toepassingen voor Stretch 4 liggen niet in het volledig vervangen van een huishoudster, maar in afgebakende taken. Denk aan ondersteuning van mensen met beperkte mobiliteit, het ophalen van objecten in een lab, of inspectie- en aanreiktaken in een zorgomgeving. Voor deze use-cases is een wielenplatform technisch én juridisch eenvoudiger te certificeren dan een zwaardere humanoïde. Dat maakt het ook aantrekkelijker voor zorginstellingen die werken onder strikte veiligheidskaders.'),
            ("h2", 'Plaats in het bredere robotica-landschap'),
            ("p", 'Stretch 4 onderstreept dat de markt voor servicerobots niet één vorm zal aannemen. Naast de humanoïden van Figure, Agility en 1X is er ruimte voor smallere, gespecialiseerde platforms die sneller commercieel volwassen zijn. Voor onderzoekers en early adopters biedt Hello Robot een platform dat openlijk werkt met ROS en Python, wat de drempel voor integratie met bestaande software laag houdt. Of de robot daadwerkelijk de stap naar grootschalige zakelijke inzet maakt, hangt af van de uitkomsten van de aangekondigde pilots.'),
            ("h2", 'Wat een Nederlandse werkgever hieraan heeft'),
            ("p", 'Voor Nederlandse organisaties die overwegen om in robotica te investeren, is Stretch 4 een nuttig referentiepunt. Het laat zien dat er tussen de dure humanoïde belofte en de bestaande cobot-arm een tussencategorie ontstaat: mobiele manipulatie tegen behapbare kosten en met een overzichtelijk risicoprofiel.'),
            ("h2", "Wat betekent dit voor Nederland?"),
            ("p", 'Voor Nederlandse zorginstellingen, revalidatiecentra en onderzoekslabs is een platform als Stretch 4 op korte termijn relevanter dan een tweebenige humanoïde: lichter, veiliger en eenvoudiger te toetsen aan Arbo-eisen en de EU AI-Act. Bij BotLease verwachten we dat juist dit type pragmatische mobiele manipulator de eerste serieuze pilots in de Nederlandse zorg- en onderwijssector zal aandrijven, ruim voordat humanoïden commercieel volwassen zijn.'),
        ],
        "sources": [
            ('IEEE Spectrum Robotics', 'https://spectrum.ieee.org/stretch-4-home-robot'),
        ],
    },
]
