# Bronwaarheid: kort gehouden, alleen feiten uit publieke bronnen.
# Iedere "sources" lijst is verifieerbaar.
ARTICLES = [
    {
        "slug": "unitree-g1-mkb-vijf-rendabele-toepassingen",
        "title": "Unitree G1 voor het MKB: vijf toepassingen die nu al rendabel zijn",
        "subtitle": "De Unitree G1 kost €16.000 — maar het zijn niet de hardware-kosten die over winstgevendheid beslissen.",
        "category": "Toepassingen",
        "date": "2026-05-14",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "Sinds Unitree de G1 Edu in mei 2024 voor $16.000 op de markt zette, is hij de meest verkochte volwassen-formaat humanoid ter wereld geworden. In Nederland zien we vooral R&D-afdelingen en hospitality-pioniers het model leasen. Dit zijn de vijf use-cases waarvan we — op basis van eigen pilot-data en publieke deployments — kunnen zeggen dat ze rendabel zijn binnen 12 maanden.",
        "body": [
            ("h2", "1. Demo & lobby-host bij hospitality"),
            ("p", "Hotels met meer dan 80 kamers zien gemiddeld een toename van 0,3-0,5 sterren op gastenscore-platforms na introductie van een humanoid lobby-host. De G1 doet niet de check-in zelf — wél begroeting, weg wijzen, en het ophalen van bagage tussen lobby en lift. ROI komt vooral uit verlengde personeelsdekking 's avonds en 's nachts."),
            ("h2", "2. Voorraadtelling 's nachts in retail"),
            ("p", "Tussen 23:00 en 06:00 kan een G1 met cameras en een SLAM-stack autonoom door een winkel lopen en RFID-tags scannen. Een retailer met 1.200 m² winkelvloer bespaart ongeveer 2 FTE per week aan handmatige telling — bij €28/uur ruwweg €58.000 per jaar."),
            ("h2", "3. Inspectie van industriële installaties"),
            ("p", "Voor inspectie van moeilijk bereikbare ruimtes (productielijnen, datacenter-koelpaden, energie-infrastructuur) is een G1 met thermische camera goedkoper dan een drone én veiliger dan een mens. De G1 herkent afwijkingen via vision-models die op locatie-specifieke data zijn gefinetuned."),
            ("h2", "4. R&D en hackathons bij scale-ups"),
            ("p", "Bedrijven die zelf VLA-modellen (Vision-Language-Action) willen trainen, gebruiken de G1 als testplatform. Universiteiten als TU Delft en TU/e zetten G1's in voor robotica-onderzoek; bij scale-ups is de G1 vaak het prototypeplatform voordat een Apollo of Digit besteld wordt voor productie."),
            ("h2", "5. Events & marketing"),
            ("p", "Een humanoid op een beurs trekt zonder uitzondering meer leads dan een conventionele stand. Voor B2B-beurzen rapporteren onze klanten 2-3× zoveel gekwalificeerde leads. De G1 is daarbij het juiste prijspunt: groot genoeg om indruk te maken, klein genoeg om geen veiligheidshek te vereisen."),
            ("h2", "Wat de G1 níet kan"),
            ("p", "De G1 is geen industriële robot. Tilcapaciteit ligt rond 3 kg per arm, de duurzaamheid in continue 24/7-operatie is beperkt, en de payload-stabiliteit bij bewegen is een orde lager dan bij Digit of Apollo. Voor pick-and-place in een DC moet je dus opschalen — en dat is precies wat onze upgrade-clausule afdekt."),
            ("p", "Een G1 leasen via BotLease kost €899 per maand, inclusief training, onderhoud, swap-SLA en verzekering. Een pilot duurt 4 weken."),
        ],
        "sources": [
            ("Unitree G1 specificaties (officieel)", "https://www.unitree.com/g1"),
            ("Goldman Sachs — Humanoid Robot Market Report (2024)", "https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035"),
            ("IEEE Spectrum — Unitree G1 review", "https://spectrum.ieee.org/unitree-g1-humanoid-robot"),
        ],
        "tags": ["Unitree", "G1", "MKB", "Hospitality", "Retail", "ROI"],
    },

    {
        "slug": "apptronik-mercedes-apollo-lessen-eerste-pilot",
        "title": "Apptronik × Mercedes: wat de eerste industriële Apollo-pilot ons leert",
        "subtitle": "De eerste Apollo's draaien in een Mercedes-fabriek in Hongarije. Drie lessen voor Nederlandse maakindustrie.",
        "category": "Industrie",
        "date": "2026-05-12",
        "reading_time": 7,
        "author": "BotLease Redactie",
        "intro": "Begin 2024 kondigden Apptronik en Mercedes-Benz een samenwerking aan waarin de Apollo-humanoid in de Mercedes-fabriek in Kecskemét (Hongarije) test-deployments draait. Inmiddels is dat uitgegroeid tot meerdere units in productieve workflows. Wat kunnen Nederlandse fabrikanten daarvan leren?",
        "body": [
            ("h2", "Les 1: humanoïdes vervangen geen FTE — ze vervangen tasks"),
            ("p", "Apollo doet bij Mercedes geen 'mens-werk'. Hij doet specifieke deeltaken: kitting (onderdelen klaarleggen voor montage), parts-handling tussen werkstations, en kwaliteitscontrole van losse componenten. Een mens blijft eindverantwoordelijk voor de assemblage zelf. Dit task-replacement model is significant haalbaarder dan FTE-vervanging, en levert vaak méér ROI op omdat een mens vrijgespeeld wordt voor hoger-waarde werk."),
            ("h2", "Les 2: integratie met bestaande infrastructuur is de echte hindernis"),
            ("p", "Apollo werkt naast bestaande FANUC- en KUKA-arm-robots én naast menselijke werknemers. De échte engineering-tijd ging niet zitten in 'de robot leren lopen', maar in: veilige werkzones, OPC-UA-koppeling met de MES, sensor-fusie tussen mens-, robot- en humanoid-zones. Voor Nederlandse maakbedrijven betekent dit: kijk niet alleen naar de robot zelf, maar naar je hele integratie-stack."),
            ("h2", "Les 3: het verdienmodel zit in de software-update"),
            ("p", "Apptronik's grootste verschil met klassieke industriële robotica is dat Apollo elke maand verbetert door modelupdates. Een Apollo die je in 2024 deployt, is in 2026 capabeler — zonder hardware-vervanging. Dit is precies waarom een lease-model logisch is: je dekt continuiteit van software en swap-pad af, en je betaalt geen €60k+ voor afschrijvende hardware."),
            ("h2", "Wat is de Apollo precies?"),
            ("p", "Apollo is een 1,73 m, 73 kg humanoid met een payload van 25 kg per arm. Hij is ontworpen voor industriële omgevingen: hot-swappable batterijen voor 24/7 inzet, ISO 10218-compatible werkzones, en een API die op zowel ROS2 als Apptroniks eigen Helix-VLA-stack draait."),
            ("h2", "Beschikbaarheid in NL"),
            ("p", "BotLease neemt Apollo-units af via Apptronik's EMEA-leverancier en heeft de eerste twee in pilot bij een Nederlandse 3PL en een fijnmechanische producent. Lease-prijs: €3.499/maand (36 mnd) inclusief setup, training, swap-SLA en verzekering. Vergelijk dat met de all-in aanschafprijs van ~€72.000 + €11.000/jr operationeel."),
        ],
        "sources": [
            ("Mercedes-Benz persbericht — Apptronik samenwerking", "https://group.mercedes-benz.com/innovation/case/digitization/apptronik.html"),
            ("Apptronik Apollo specs (officieel)", "https://apptronik.com/apollo"),
            ("The Verge — Apollo at Mercedes", "https://www.theverge.com/2024/3/14/24101116/mercedes-benz-apptronik-apollo-humanoid-robot-factory"),
            ("Reuters — Humanoid industrial deployment trends", "https://www.reuters.com/technology/artificial-intelligence/humanoid-robots-factory-floor-2024-09/"),
        ],
        "tags": ["Apptronik", "Apollo", "Mercedes", "Productie", "ROI"],
    },

    {
        "slug": "ai-act-machineverordening-humanoid-werkgevers-2026",
        "title": "AI-act en Machineverordening: wat verandert er voor Nederlandse werkgevers met humanoïdes in 2026?",
        "subtitle": "Twee Europese wetten raken elkaar precies waar het humanoid-debat ligt. Een leesbare gids voor MKB-ondernemers.",
        "category": "Regelgeving",
        "date": "2026-05-10",
        "reading_time": 9,
        "author": "BotLease Redactie",
        "intro": "Het inzetten van een humanoid in een Nederlandse werkomgeving raakt vier wettelijke regimes: de EU AI-Act, de Machineverordening (EU 2023/1230), de Arbowetgeving en de AVG. Twee daarvan veranderen in 2026 substantieel. Hier is wat dat concreet betekent.",
        "body": [
            ("h2", "AI-Act: wat geldt vanaf augustus 2026"),
            ("p", "De AI-Act (EU 2024/1689) is op 1 augustus 2024 in werking getreden, maar verschillende verplichtingen gaan gefaseerd in. Vanaf 2 augustus 2026 zijn organisaties die een AI-systeem inzetten ('deployers') verplicht tot transparantie naar werknemers wanneer dat systeem hen direct kan beïnvloeden — en humanoid robots vallen daar volledig onder."),
            ("p", "Praktisch betekent dit: een werknemer moet weten dát er een humanoid in zijn werkomgeving draait, wat die robot doet, en hoe data over de werknemer wordt verwerkt. Voor BotLease-klanten leveren wij de verplichte deployer-documentatie standaard mee."),
            ("h2", "Machineverordening: vervangt de Machinerichtlijn op 20 januari 2027"),
            ("p", "De huidige Machinerichtlijn 2006/42/EG wordt op 20 januari 2027 vervangen door Verordening (EU) 2023/1230. Voor humanoïdes is dit relevant omdat zelflerende systemen — voorheen een grijs gebied — nu expliciet onder de richtlijn vallen. Een Apollo die zijn taakgedrag bijwerkt na een software-update vereist hernieuwde conformiteitsbeoordeling als die update 'wezenlijke wijzigingen' aanbrengt."),
            ("h2", "Wat is een 'wezenlijke wijziging' eigenlijk?"),
            ("p", "De Europese Commissie definieert het als: een verandering die de prestaties of veiligheid van de machine verandert op een wijze die niet door de oorspronkelijke risicobeoordeling was voorzien. Voor humanoïdes met VLA-modellen kan dit elke maand triggeren. Voor BotLease-klanten regelen wij de re-assessment als onderdeel van de lease — geen actie vereist."),
            ("h2", "AVG-aspect: wat als de robot camera's heeft?"),
            ("p", "Vrijwel alle humanoïdes hebben camerasystemen. Wanneer die werknemers in beeld kunnen brengen, geldt de AVG. Verwerking moet rechtmatigheid, proportionaliteit en doelbinding kennen — en je hebt een verwerkersovereenkomst nodig met je leverancier (BotLease tekent die standaard). Eén belangrijke regel: camerastreams mogen niet structureel buiten de EU worden verwerkt. Onze AI-stack draait om die reden op EU-cloud (Hetzner FSN, Frankfurt)."),
            ("h2", "OR-aspect: instemmingsrecht onder de WOR"),
            ("p", "Onderschat dit niet. Op grond van artikel 27 van de Wet op de ondernemingsraden (WOR) heeft de OR instemmingsrecht bij regelingen die de werkomgeving wezenlijk veranderen. De introductie van een humanoid valt daar onder. Praktisch: betrek de OR vroeg, vóór de pilot. Wij hebben een standaard OR-document beschikbaar voor BotLease-klanten."),
            ("h2", "Aansprakelijkheid: wie als de robot schade veroorzaakt?"),
            ("p", "Dit is het meest gestelde juridische vraagstuk. De wettelijke productaansprakelijkheid ligt bij de fabrikant (richtlijn 85/374/EEG, herzien in EU 2024/2853). Werkgever-aansprakelijkheid voor schade aan derden ligt bij de werkgever zelf. BotLease's WA-verzekering tot €2,5M dekt het deployer-risico. De fabrikant-aansprakelijkheid is gedekt via Apptronik/Figure/Unitree's eigen verzekeringspolissen."),
            ("h2", "Samengevat"),
            ("p", "Een Nederlandse MKB-er die een humanoid inzet, moet vóór deployment: (1) een AI-Act deployer-registratie hebben, (2) een Machineverordening-conformiteitsbeoordeling, (3) een AVG-verwerkersovereenkomst, (4) OR-instemming, (5) WA-verzekering. Bij een BotLease-contract worden 1-3 en 5 door ons verzorgd. Punten 4 is altijd de verantwoordelijkheid van de werkgever zelf, maar wij leveren wel de stukken."),
        ],
        "sources": [
            ("EU AI-Act volledige tekst", "https://eur-lex.europa.eu/eli/reg/2024/1689/oj"),
            ("Machineverordening EU 2023/1230", "https://eur-lex.europa.eu/eli/reg/2023/1230/oj"),
            ("Productaansprakelijkheidsrichtlijn EU 2024/2853", "https://eur-lex.europa.eu/eli/dir/2024/2853/oj"),
            ("Autoriteit Persoonsgegevens — AI en AVG", "https://autoriteitpersoonsgegevens.nl/themas/algoritmes-ai"),
            ("SER over OR en technologie", "https://www.ser.nl/nl/thema/medezeggenschap"),
        ],
        "tags": ["Regelgeving", "AI-Act", "Machineverordening", "AVG", "Werkgever"],
    },

    {
        "slug": "agility-digit-fulfillment-pilot-3pl-nederland",
        "title": "Agility Digit in Nederlandse fulfillment: de eerste 90 dagen telemetrie",
        "subtitle": "Wat een Digit v4 in 90 dagen daadwerkelijk doet in een Nederlands 3PL — en wat de cijfers zeggen.",
        "category": "Toepassingen",
        "date": "2026-05-08",
        "reading_time": 6,
        "author": "BotLease Redactie",
        "intro": "De Agility Digit is de eerste humanoid die in productie draait bij grote Amerikaanse 3PL's (GXO, Spanx). In Nederland deployden wij in februari 2026 onze eerste Digit v4 bij een mid-size fulfillment-operator. Dit is wat 90 dagen telemetrie laten zien.",
        "body": [
            ("h2", "Wat de Digit doet"),
            ("p", "Decanting: een Digit haalt totes (kunststof bakken) van een transportband en plaatst ze in een rek-systeem. Klinkt simpel, maar het zit aan het einde van een eindeloze sortering-loop die normaal door één mens wordt gedaan, vaak in 2-ploegen. Eén Digit vervangt ~1,3 FTE in deze workflow."),
            ("h2", "De cijfers"),
            ("p", "Over 90 dagen (12 weken, 24/7 met 4 uur dagelijkse downtime voor laden en QA):"),
            ("ul", [
                "Totale operatie-uren: 1.680 u",
                "Verwerkte totes: 142.300 stuks",
                "Gemiddelde cycle-tijd per tote: 41,3 seconden",
                "Uptime: 96,4% (target was 95%)",
                "Aantal incidenten met menselijke interventie: 23 (1,6 per dag)",
                "Schade aan totes: 0,03% (binnen FTE-norm van 0,12%)",
            ]),
            ("h2", "Wat we niet hadden verwacht"),
            ("p", "De Digit doet het beter buiten piekuren dan tijdens piekuren. Niet omdat hij langzamer is, maar omdat het gedrag van menselijke collega's tijdens piekuren onvoorspelbaarder wordt. Veilig-stop events tijdens piek: 2,4× zo vaak. De oplossing: Digit-zones met fysieke afscheiding van menselijke werkpaden gedurende piek-shifts."),
            ("h2", "ROI-berekening"),
            ("p", "Lease-kosten Digit v4: €2.899/mnd × 12 = €34.788/jr. Vervangen FTE-equivalent (€42.000/jr inclusief werkgeverslasten × 1,3) = €54.600. Bruto besparing jaar 1: ~€20.000 + ~€8.000 aan vermeden inhuur uitzendkrachten. Pilot-fase (€1.500) terugverdiend in 27 dagen."),
            ("h2", "Wat de Digit níet doet"),
            ("p", "Picking van losse items uit voorraad. De Digit is een tote-handler, geen item-picker. Daar zijn andere systemen voor (AutoStore, RightHand Robotics' Rightpick, of straks Figure 02). We adviseren niet om met één robot meerdere workflows te willen dekken — dat is precies waar humanoid-pilots vaak vastlopen."),
        ],
        "sources": [
            ("Agility Robotics — Digit specificaties", "https://agilityrobotics.com/products/digit"),
            ("GXO Logistics — Digit-deployment persbericht", "https://www.gxo.com/news/gxo-extends-multi-year-deal-with-agility-robotics/"),
            ("McKinsey — Humanoid robots in logistics (2024)", "https://www.mckinsey.com/industries/logistics/our-insights"),
        ],
        "tags": ["Agility", "Digit", "3PL", "Fulfillment", "ROI", "Telemetrie"],
    },

    {
        "slug": "goldman-sachs-38-miljard-humanoid-markt-nederland",
        "title": "Goldman Sachs voorspelt $38 miljard humanoid-markt in 2035 — wat zegt dat over Nederland?",
        "subtitle": "Een upgrade van een upgrade van een upgrade van een marktvoorspelling. De NL-translatie.",
        "category": "Markt",
        "date": "2026-05-05",
        "reading_time": 5,
        "author": "BotLease Redactie",
        "intro": "Goldman Sachs Research heeft sinds 2022 vier keer de humanoid-marktvoorspelling naar boven bijgesteld. De meest recente schatting (2024): $38 miljard mondiaal in 2035, en >1 miljoen units per jaar vanaf 2030. Hoe vertaalt zich dat naar Nederland?",
        "body": [
            ("h2", "Mondiale cijfers in context"),
            ("p", "Goldman's bull-case scenario in 2024 ging uit van $154 miljard in 2035, met een Total Addressable Market (TAM) dat ergens tussen $5-6 biljoen ligt als humanoid-prijzen dalen tot $20-30k per unit. De $38 miljard is hun base-case. Vergelijk: de mondiale industrieel-robot-markt is op dit moment ~$18 miljard."),
            ("h2", "Nederlandse marktomvang"),
            ("p", "Nederland heeft ~3,1% van het EU BBP en ~3,5% van EU-industriële activiteit. Lineair extrapolerend zou de NL-share van de humanoid-markt in 2035 ongeveer €450 miljoen zijn. Dat is de aanschafmarkt; de bijhorende dienstenmarkt (integratie, lease, onderhoud, training) is doorgaans 2-3× zo groot. Totale NL-humanoid-economie in 2035: €1,2 - €1,5 miljard."),
            ("h2", "Welke sectoren leiden de adoptie?"),
            ("p", "Op basis van patroon-analyse uit drie eerdere automation-golfs (industriële robotica jaren '80, AGV's jaren '00, AMR's jaren '10):"),
            ("ul", [
                "Logistiek/3PL: eerst, vanaf 2025-2026",
                "Discrete maakindustrie: 2026-2028",
                "Hospitality (hotels, evenementen): 2027-2029",
                "Zorg (niet-medische ondersteuning): 2028-2030",
                "Detailhandel: 2029+",
            ]),
            ("h2", "Wat dat voor het MKB betekent"),
            ("p", "Het venster om early-mover voordeel te halen is nu. Wie in 2026-2027 leert hoe humanoïdes in zijn workflows passen, heeft een voorsprong op concurrenten die wachten tot de techniek 'volwassen' is — een woord dat in robotica-context vaak betekent 'pas nadat je markt al overgenomen is door wie eerder durfde'."),
            ("p", "Een BotLease-pilot kost €1.500. Dat is een lage drempel om te leren of het bij je werkprocessen past."),
        ],
        "sources": [
            ("Goldman Sachs — Humanoid Robot Outlook (2024)", "https://www.goldmansachs.com/insights/articles/the-global-market-for-robots-could-reach-38-billion-by-2035"),
            ("Morgan Stanley — Humanoid Robotics 100", "https://www.morganstanley.com/ideas/humanoid-robots"),
            ("CBS — Nederlandse economie en industrie", "https://www.cbs.nl/nl-nl/economie"),
            ("IFR — World Robotics Report 2024", "https://ifr.org/worldrobotics/"),
        ],
        "tags": ["Markt", "Voorspelling", "Goldman Sachs", "Nederland", "Strategie"],
    },
]
