# BotLease robot data
# Bronwaarheid: marktstand mei 2026. Prijzen op basis van publieke aanschafprijzen
# + 30% marge + 25% service/onderdelen + 8% verzekering, gedeeld over 36 mnd lease.
# Categorieën:
#   "available" → direct te leasen (kern aanbieding)
#   "waitlist"  → bevestigd in productie maar nog niet beschikbaar voor EU MKB derden

ROBOTS = [
    # ────────────────────────────── EU-gebouwd (strategische kern) ──────────
    {
        "slug": "neura-4ne1-mini",
        "name": "NEURA 4NE-1 Mini",
        "vendor": "NEURA Robotics",
        "vendor_country": "Duitsland",
        "category": "available",
        "tier": "eu",
        "badge": "EU-gebouwd",
        "photo": "/img/robots/neura-4ne1-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Made in Germany - EU AI Act ready vanaf dag 1.",
        "short": "Compacte cognitieve humanoid uit Metzingen (DE). Porsche-design, artificial skin, Neuraverse OS. Korte EU-supply chain, Duitstalige support, GDPR + EU AI Act compliance baked-in.",
        "height_cm": 165,
        "weight_kg": 60,
        "payload_kg": 15,
        "battery_hours": 4,
        "dof": 32,
        "speed_ms": 1.2,
        "lease_eur": 1295,
        "setup_eur": 2500,
        "purchase_eur": 22000,
        "use_cases": [
            "Cobotwerk in lichte productie / assemblage",
            "R&D platform voor universiteiten en scale-ups",
            "Demo/event-host met Duitstalige speech",
            "Lichte service-taken in zorginstellingen",
        ],
        "specs_detail": [
            ("AI", "Neuraverse OS, fleet-learning + on-device LLM"),
            ("Sensoren", "Artificial skin (proximity), depth-camera, 6-mic array"),
            ("Veiligheid", "CE-gecertificeerd, EN ISO 13482 cobot-compliant"),
            ("Compliance", "EU AI Act + Machineverordening 2023/1230 ready"),
            ("Levertijd", "Doorgaans 6-10 weken na intake"),
        ],
        "tags": ["EU-gebouwd", "Cobot", "R&D", "Service"],
        "vendor_url": "https://neura-robotics.com/products/4ne1/",
        "video_id": "4j_vgDESuDs",
        "video_title": "NEURA Robotics 4NE-1 derde generatie - Automatica 2025",
    },
    {
        "slug": "neura-4ne1-gen3",
        "name": "NEURA 4NE-1 Gen 3.5",
        "vendor": "NEURA Robotics",
        "vendor_country": "Duitsland",
        "category": "available",
        "tier": "eu",
        "badge": "EU Flagship",
        "photo": "/img/robots/neura-4ne1-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Europese flagship - 100 kg payload, Porsche-design, Bosch-partner.",
        "short": "Full-size industriële humanoid uit Duitsland. Porsche-design Gen 3.5 met 100 kg liftcapaciteit en Bosch als productiepartner. Voor maakindustrie, logistiek en mobiele inspectie.",
        "height_cm": 180,
        "weight_kg": 80,
        "payload_kg": 100,
        "battery_hours": 4,
        "dof": 39,
        "speed_ms": 1.5,
        "lease_eur": 5950,
        "setup_eur": 6500,
        "purchase_eur": 98000,
        "use_cases": [
            "Industriële assemblage (auto, machine, electronics)",
            "Heavy-duty pick & place in 3PL en productie",
            "Mobiele inspectie van installaties + reporting",
            "Co-werken naast menselijke operators (cobot-mode)",
        ],
        "specs_detail": [
            ("AI", "Neuraverse - fleet trained, transfer learning"),
            ("Hands", "16 DoF per hand, force-feedback per vinger"),
            ("Veiligheid", "EU Machineverordening 2023/1230 conform"),
            ("Compliance", "EU AI Act high-risk assessment compleet"),
            ("Bosch", "Productie + onderdelen via Bosch industrial chain"),
        ],
        "tags": ["EU-gebouwd", "Industrie", "Heavy-duty", "Cobot"],
        "vendor_url": "https://neura-robotics.com/products/4ne1/",
        "video_id": "4j_vgDESuDs",
        "video_title": "NEURA Robotics 4NE-1 derde generatie - Automatica 2025",
    },
    {
        "slug": "pal-kangaroo",
        "name": "PAL Kangaroo",
        "vendor": "PAL Robotics",
        "vendor_country": "Spanje",
        "category": "available",
        "tier": "eu",
        "badge": "EU-veteraan",
        "photo": "/img/robots/kangaroo-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "20+ jaar field-proven uit Barcelona - ROS-native.",
        "short": "Bipedal humanoid van Europa's oudste robotica-fabrikant (sinds 2004). ROS-native, geoptimaliseerd voor mobile manipulation en onderzoek. Spaanse engineering, EU-supply.",
        "height_cm": 178,
        "weight_kg": 75,
        "payload_kg": 20,
        "battery_hours": 4,
        "dof": 35,
        "speed_ms": 1.4,
        "lease_eur": 5750,
        "setup_eur": 5500,
        "purchase_eur": 95000,
        "use_cases": [
            "Onderzoek en universitair gebruik (ROS-native)",
            "Mobile manipulation in laboratoria",
            "Lichte logistiek + tote-handling",
            "Service-taken in instellingen",
        ],
        "specs_detail": [
            ("Software", "ROS 2 native, open API, Linux"),
            ("Heritage", "PAL bouwt sinds 2004 humanoids (REEM, TIAGo, Kangaroo)"),
            ("Compliance", "CE-gemarkeerd, EU-supply chain"),
            ("Support", "EU-engineers, Spaanstalig + Engelstalig"),
        ],
        "tags": ["EU-gebouwd", "Onderzoek", "ROS", "Veteraan"],
        "vendor_url": "https://pal-robotics.com/robots/kangaroo/",
        "video_id": "G7riD4yb1tg",
        "video_title": "PAL Robotics Kangaroo Pro - bipedal walking demo",
    },
    {
        "slug": "pal-tiago-pro",
        "name": "PAL TIAGo Pro",
        "vendor": "PAL Robotics",
        "vendor_country": "Spanje",
        "category": "available",
        "tier": "eu",
        "badge": "EU-gebouwd",
        "photo": "/img/robots/tiago-pro-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Mobile manipulator - onderzoekslievelinge van EU-universiteiten.",
        "short": "Wheeled humanoid manipulator (geen bipedal). Field-proven in 100+ Europese onderzoekslabs en zorginstellingen. Snel inzetbaar, lage operationele risico.",
        "height_cm": 145,
        "weight_kg": 70,
        "payload_kg": 10,
        "battery_hours": 8,
        "dof": 17,
        "speed_ms": 1.0,
        "lease_eur": 3950,
        "setup_eur": 3000,
        "purchase_eur": 65000,
        "use_cases": [
            "Service-taken in zorginstellingen en bibliotheken",
            "Onderzoeksplatform voor HRI / manipulation",
            "Receptie en lobby-host",
            "Materiaaltransport binnen gebouwen",
        ],
        "specs_detail": [
            ("Type", "Wheeled humanoid (geen bipedal)"),
            ("Software", "ROS 2 native, open-source SDK"),
            ("Heritage", "100+ deployments in EU sinds 2014"),
            ("Compliance", "CE-gemarkeerd, EN ISO 13482"),
        ],
        "tags": ["EU-gebouwd", "Service", "Onderzoek", "Wheeled"],
        "vendor_url": "https://pal-robotics.com/robots/tiago-pro/",
        "video_id": "gcgMAngLLZQ",
        "video_title": "PAL Robotics TIAGo Pro - Empowering Mobile Manipulation",
    },
    {
        "slug": "pollen-reachy-2",
        "name": "Pollen Reachy 2",
        "vendor": "Pollen Robotics",
        "vendor_country": "Frankrijk",
        "category": "available",
        "tier": "eu",
        "badge": "Open-source",
        "photo": "/img/robots/reachy2-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Open-source, Hugging Face-owned - ideaal voor AI-onderzoek.",
        "short": "Open-source humanoid uit Frankrijk, sinds 2024 onderdeel van Hugging Face. Modulair (single/dual arm + mobile base), tweehandig + bewegelijk hoofd. Geoptimaliseerd voor AI-training en VLA-modelontwikkeling.",
        "height_cm": 140,
        "weight_kg": 30,
        "payload_kg": 3,
        "battery_hours": 6,
        "dof": 28,
        "speed_ms": 0.8,
        "lease_eur": 4150,
        "setup_eur": 3500,
        "purchase_eur": 68000,
        "use_cases": [
            "AI-onderzoek: VLA-model training, imitation learning",
            "Demonstrator voor humanoid AI op events",
            "Onderwijs en hackathons",
            "Manipulation-onderzoek in labs",
        ],
        "specs_detail": [
            ("Software", "Open-source SDK, Hugging Face LeRobot framework"),
            ("Modulair", "Single/dual arm, mobile base optioneel"),
            ("Heritage", "Pollen 2016, overgenomen door Hugging Face 2024"),
            ("Community", "Wereldwijde open-source community"),
        ],
        "tags": ["EU-gebouwd", "Open-source", "AI-onderzoek", "Modulair"],
        "vendor_url": "https://www.pollen-robotics.com/reachy/",
        "video_id": "SgTWHS-IwoE",
        "video_title": "Meet Reachy 2 - The Human-Piloted Robot by Pollen Robotics",
    },

    # ────────────────────────────── Direct beschikbaar (Aziatisch) ──────────
    {
        "slug": "unitree-r1",
        "name": "Unitree R1",
        "vendor": "Unitree Robotics",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Vanaf €290",
        "photo": "/img/robots/r1-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "De goedkoopste full-bipedal humanoid op de markt.",
        "short": "Unitree's instapper voor scholen, evenementen en kleine bedrijven. Vanaf €4.900 koop, lease vanaf €290/mnd. Démocratiseert humanoid technologie voor markten die voorheen onbereikbaar waren.",
        "height_cm": 121,
        "weight_kg": 25,
        "payload_kg": 3,
        "battery_hours": 2,
        "dof": 26,
        "speed_ms": 1.5,
        "lease_eur": 290,
        "setup_eur": 1200,
        "purchase_eur": 8000,
        "use_cases": [
            "Demo + marketing op beurzen en events",
            "Onderwijs (PO/VO/HBO/WO robotica-curriculum)",
            "Marketing-stunts en social-media activaties",
            "Lichte hospitality (begroeting, weg wijzen)",
        ],
        "specs_detail": [
            ("Prijspunt", "Marktdisruptie - onder €5k aanschaf"),
            ("Levertijd", "6-8 weken via Unitree EU-distributeurs"),
            ("Toepassing", "Niet voor productieve werkvloer, wel demo"),
        ],
        "tags": ["Instap", "Education", "Demo", "Events"],
        "vendor_url": "https://www.unitree.com/r1",
        "video_id": "v1Q4Su54iho",
        "video_title": "Unitree R1 Intelligent Companion - officiële introductie",
    },
    {
        "slug": "unitree-g1",
        "name": "Unitree G1 Edu",
        "vendor": "Unitree Robotics",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Bestseller",
        "photo": "/img/robots/g1-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Meest verkochte volwassen-formaat humanoid wereldwijd.",
        "short": "Unitree's bestseller. Compact (1,27 m), agile, betaalbaar. De facto standaardplatform voor R&D bij scale-ups en universiteiten. Mass production sinds 2024.",
        "height_cm": 127,
        "weight_kg": 35,
        "payload_kg": 3,
        "battery_hours": 2,
        "dof": 23,
        "speed_ms": 2.0,
        "lease_eur": 1295,
        "setup_eur": 1800,
        "purchase_eur": 23000,
        "use_cases": [
            "R&D platform bij scale-ups en universiteiten",
            "Hospitality (lobby-host, begroeting)",
            "Voorraadtelling 's nachts (retail SLAM)",
            "Inspectie van moeilijk bereikbare ruimtes",
        ],
        "specs_detail": [
            ("Heritage", "Bestseller sinds mei 2024 ($16k launch)"),
            ("Levertijd", "Doorgaans 6-8 weken na intake"),
            ("DoF", "23-43 afhankelijk van configuratie"),
        ],
        "tags": ["Bestseller", "R&D", "Hospitality", "Inspectie"],
        "vendor_url": "https://www.unitree.com/g1",
        "video_id": "Nkh6RUocD8c",
        "video_title": "Unitree G1 - world's first humanoid kip-up demonstration",
    },
    {
        "slug": "unitree-h1-2",
        "name": "Unitree H1-2",
        "vendor": "Unitree Robotics",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Industrieel",
        "photo": "/img/robots/h1-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Full-size industriële kracht - kwart van Westerse prijs.",
        "short": "Unitree's full-size industriële humanoid. 30 kg payload, robuuste constructie. Voor R&D, payload-heavy demo en lichte logistiek.",
        "height_cm": 180,
        "weight_kg": 70,
        "payload_kg": 30,
        "battery_hours": 2,
        "dof": 27,
        "speed_ms": 3.3,
        "lease_eur": 6650,
        "setup_eur": 5500,
        "purchase_eur": 110000,
        "use_cases": [
            "Industriële R&D met realistische payload",
            "Lichte logistiek + tote-handling",
            "Inspectie van zware installaties",
            "Events en demonstraties op industrieschaal",
        ],
        "specs_detail": [
            ("Levertijd", "Doorgaans 6-8 weken na intake"),
            ("Payload", "30 kg, hoogste in zijn prijsklasse"),
            ("Snelheid", "Tot 3,3 m/s - een van de snelste bipedals"),
        ],
        "tags": ["Industrieel", "Heavy-duty", "Payload"],
        "vendor_url": "https://www.unitree.com/h1",
        "video_id": "sfcqAZcWoMo",
        "video_title": "Unitree H1 - recordbrekende snelheid 22.4 MPH",
    },
    {
        "slug": "unitree-h2",
        "name": "Unitree H2",
        "vendor": "Unitree Robotics",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Service",
        "photo": "/img/robots/h2-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Bionisch gezicht + sociale AI - beste value full-size.",
        "short": "Unitree's service-georiënteerde flagship. Bionisch gezicht voor sociale interactie, 2070 TOPS AI-chip. Voor hospitality, retail en lichte service-taken waar interactie centraal staat.",
        "height_cm": 180,
        "weight_kg": 65,
        "payload_kg": 15,
        "battery_hours": 3,
        "dof": 31,
        "speed_ms": 2.5,
        "lease_eur": 2750,
        "setup_eur": 2500,
        "purchase_eur": 45000,
        "use_cases": [
            "Hospitality met sociale interactie (hotel, restaurant)",
            "Retail-host + voorraadtelling",
            "Receptie en lobby-werk in gebouwen",
            "Educatie en demo's voor publiek",
        ],
        "specs_detail": [
            ("AI-chip", "2070 TOPS on-device - vision + speech lokaal"),
            ("Sociaal", "Bionisch gezicht met expressie"),
            ("Joint torque", "360 N·m - sterk voor zijn formaat"),
        ],
        "tags": ["Service", "Hospitality", "Sociale-AI"],
        "vendor_url": "https://www.unitree.com/h2",
        "video_id": "eUdBIFkMh-M",
        "video_title": "Unitree H2 - Destiny Awakening (officiële introductie)",
    },
    {
        "slug": "engineai-se01",
        "name": "EngineAI SE01",
        "vendor": "EngineAI",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Snelste",
        "photo": "/img/robots/se01-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Eerste humanoid met écht natuurlijke menselijke gang.",
        "short": "Shenzhen-startup met expertise uit UC Berkeley, Tsinghua, Purdue. Neural-network gait - bekend om de meest natuurlijke loopbeweging in zijn klasse. Lichtere en snellere optie naast Unitree.",
        "height_cm": 170,
        "weight_kg": 55,
        "payload_kg": 10,
        "battery_hours": 2,
        "dof": 32,
        "speed_ms": 2.0,
        "lease_eur": 1590,
        "setup_eur": 2200,
        "purchase_eur": 28000,
        "use_cases": [
            "Demo + events waar natuurlijke beweging indruk maakt",
            "R&D in locomotie en neural-network gait",
            "Lichte service en hospitality",
            "Onderzoek naar embodied AI",
        ],
        "specs_detail": [
            ("Gait", "End-to-end neural net - vloeibare menselijke gang"),
            ("Compute", "NVIDIA + Intel dual-processor"),
            ("Sensoren", "Depth camera, 360° LiDAR (Engine Sense)"),
            ("Status", "Commercieel beschikbaar sinds eind 2024"),
        ],
        "tags": ["R&D", "Gait", "Neural", "Service"],
        "vendor_url": "https://www.engineai.com/",
        "video_id": "wlQ2Ep0g7gg",
        "video_title": "EngineAI SE01 - natural human-like walking gait",
    },
    {
        "slug": "ubtech-walker-s2",
        "name": "UBTECH Walker S2",
        "vendor": "UBTECH",
        "vendor_country": "China",
        "category": "available",
        "tier": "value",
        "badge": "Auto-industrie",
        "photo": "/img/robots/walker-s-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Eerste Chinese full-size humanoid in mass production.",
        "short": "Bewezen in BYD- en Foxconn-fabrieken. Mass production sinds nov 2025 - orderportefeuille >800M yuan (€100M). Voor productieve automotive en electronics assemblage.",
        "height_cm": 175,
        "weight_kg": 76,
        "payload_kg": 25,
        "battery_hours": 4,
        "dof": 41,
        "speed_ms": 2.0,
        "lease_eur": 5750,
        "setup_eur": 4500,
        "purchase_eur": 95000,
        "use_cases": [
            "Auto-industrie: assemblage, kwaliteitscontrole",
            "Electronics: SMT-bestukking + handling",
            "Heavy-duty kitting in productie",
            "Material handling in fabrieken",
        ],
        "specs_detail": [
            ("Productie", "Mass production sinds nov 2025 - BYD/Foxconn"),
            ("Deployments", ">800M yuan in orders (~€100M)"),
            ("Sterk punt", "Hot-swap batterij, 24/7 operatie mogelijk"),
        ],
        "tags": ["Auto-industrie", "Mass-production", "Heavy-duty"],
        "vendor_url": "https://www.ubtrobot.com/en/business/walker/",
        "video_id": "WSn5Atk9ojo",
        "video_title": "UBTECH Walker S2 - World's First Mass Deployment of Humanoid Robots",
    },

    # ────────────────────────────── Wachtlijst 2027 ──────────────────────────
    {
        "slug": "apptronik-apollo",
        "name": "Apptronik Apollo",
        "vendor": "Apptronik",
        "vendor_country": "Verenigde Staten",
        "category": "waitlist",
        "tier": "premium",
        "badge": "Wachtlijst 2027",
        "photo": "/img/robots/apollo-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Mercedes-Benz pilot - niet leverbaar voor derden in 2026.",
        "short": "Industriële humanoid, $935M funding ($5B valuation feb 2026). Pilots bij Mercedes Sindelfingen en GXO Wentzville. Apptronik verkoopt 2026 alleen aan select enterprise (target: <$50k unit-prijs vanaf 2027). BotLease accepteert refundable reserveringen - wij bemiddelen zodra 3rd-party verkoop voor de EU opengaat. Genoemde lease-prijs is indicatief.",
        "height_cm": 173,
        "weight_kg": 73,
        "payload_kg": 25,
        "battery_hours": 4,
        "dof": 38,
        "speed_ms": 1.5,
        "lease_eur": 3499,
        "setup_eur": 5500,
        "purchase_eur": 48000,
        "use_cases": [
            "Industriële kitting + parts-handling (Mercedes use-case)",
            "Mobile manipulation in 3PL (GXO use-case)",
            "Kwaliteitscontrole in productie",
        ],
        "specs_detail": [
            ("Pilots", "Mercedes-Benz Sindelfingen (DE), GXO Wentzville"),
            ("Funding", "$935M opgehaald, $5B valuation"),
            ("Commerciële verkoop", "Verwacht eind 2026 / begin 2027"),
        ],
        "tags": ["Wachtlijst", "Industrieel", "Premium"],
        "vendor_url": "https://apptronik.com/apollo",
        "video_id": "TfUOg38iXxo",
        "video_title": "Mercedes-Benz testing Apollo humanoid robot in production",
    },
    {
        "slug": "figure-02",
        "name": "Figure 02 / 03",
        "vendor": "Figure AI",
        "vendor_country": "Verenigde Staten",
        "category": "waitlist",
        "tier": "premium",
        "badge": "Wachtlijst 2027",
        "photo": "/img/robots/figure02-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "BMW Spartanburg deployment - Figure 03 enterprise-only, géén EU-verkoop in 2026.",
        "short": "California-startup met BMW als enterprise-klant (Spartanburg en Leipzig). Figure 02 is uit productie sinds okt 2025; Figure 03 wordt enkel aan select enterprise partners geleverd. BotLease accepteert refundable reserveringen en bemiddelt zodra Figure 3rd-party EU-verkoop opent. Genoemde lease-prijs is indicatief.",
        "height_cm": 170,
        "weight_kg": 70,
        "payload_kg": 20,
        "battery_hours": 5,
        "dof": 36,
        "speed_ms": 1.2,
        "lease_eur": 3899,
        "setup_eur": 6000,
        "purchase_eur": 55000,
        "use_cases": [
            "Auto-industrie: chassis-assemblage (BMW use-case)",
            "Productie met hoge precisie",
            "Multi-task warehouse operations",
        ],
        "specs_detail": [
            ("Pilots", "BMW Spartanburg + Leipzig productie"),
            ("Status", "Figure 03 in productie - enterprise pilots only"),
            ("EU-verkoop", "Geen open verkoop 2026 - reserveren mogelijk"),
        ],
        "tags": ["Wachtlijst", "Auto", "Premium"],
        "vendor_url": "https://www.figure.ai/",
        "video_id": "CgLwDbbledA",
        "video_title": "BMW is testing the Figure 02 humanoid robot",
    },
    {
        "slug": "agility-digit",
        "name": "Agility Digit v4",
        "vendor": "Agility Robotics",
        "vendor_country": "Verenigde Staten",
        "category": "waitlist",
        "tier": "premium",
        "badge": "Op aanvraag",
        "photo": "/img/robots/digit-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Bewezen 3PL-humanoid - alleen op aanvraag, Agility verkoopt direct.",
        "short": "100.000+ totes verwerkt bij Amazon en GXO. Agility Robotics verkoopt uitsluitend zelf via Robots-as-a-Service (~$30/uur) aan enterprise klanten - er is geen 3rd-party reseller-kanaal. BotLease faciliteert in 2026 enkel op aanvraag voor enterprise pilots (≥3 units). Genoemde lease-prijs is indicatief; werkelijk traject loopt via Agility-direct.",
        "height_cm": 175,
        "weight_kg": 65,
        "payload_kg": 16,
        "battery_hours": 4,
        "dof": 32,
        "speed_ms": 1.5,
        "lease_eur": 4250,
        "setup_eur": 4500,
        "purchase_eur": 70000,
        "use_cases": [
            "3PL: tote- en pakkethandling (Amazon use-case)",
            "Fulfillment: decanting en sortering",
            "Material handling tussen werkstations",
        ],
        "specs_detail": [
            ("Heritage", "100.000+ totes bij Amazon/GXO/Toyota"),
            ("Status", "Op aanvraag - limited availability voor EU MKB in 2026"),
            ("V4 launch", "Verwacht dec 2026"),
        ],
        "tags": ["Wachtlijst", "3PL", "Premium"],
        "vendor_url": "https://www.agilityrobotics.com/",
        "video_id": "Xq_-OTQgzf0",
        "video_title": "Digit: GXO's human-centric warehouse robot",
    },
    {
        "slug": "1x-neo",
        "name": "1X NEO",
        "vendor": "1X Technologies",
        "vendor_country": "Noorwegen",
        "category": "waitlist",
        "tier": "premium",
        "badge": "EU shipping Q1 2027",
        "photo": "/img/robots/neo-norm.webp",
        "photo_dims": (1000, 1250),
        "tagline": "Consumer-grade humanoid - eerste EU-zendingen Q1 2027.",
        "short": "Noorse oorsprong (overgenomen door OpenAI). Consumenten-georiënteerd, soft 3D-lattice exterior, near-silent operation. 1X verkoopt direct: $20.000 koop óf $499/maand abonnement - daarmee is BotLease's lease-marge dun. Wij accepteren reserveringen voor B2B-deployments waar BotLease wél waarde toevoegt (vlootbeheer, training, integratie, SLA). Genoemde lease-prijs is indicatief.",
        "height_cm": 168,
        "weight_kg": 30,
        "payload_kg": 5,
        "battery_hours": 6,
        "dof": 44,
        "speed_ms": 1.0,
        "lease_eur": 1999,
        "setup_eur": 2500,
        "purchase_eur": 20000,
        "use_cases": [
            "Hospitality met zachte interactie",
            "Lichte zorg en huishoudelijke ondersteuning",
            "Retail-host in publieke ruimtes",
        ],
        "specs_detail": [
            ("Materiaal", "Soft 3D-lattice exterior, knitted 'sweater'"),
            ("Hands", "44 DoF totaal (22 per hand)"),
            ("Geluid", "22 dB operatie - near-silent"),
            ("EU shipping", "Q1 2027 verwacht"),
        ],
        "tags": ["Wachtlijst", "Service", "Consumer"],
        "vendor_url": "https://www.1x.tech/neo",
        "video_id": "uVcBa6NXAbk",
        "video_title": "1X NEO Gamma - Another Step Closer to Home",
    },
]


# Quick lookups
def by_slug(slug: str) -> dict | None:
    for r in ROBOTS:
        if r["slug"] == slug:
            return r
    return None


def available_robots() -> list[dict]:
    return [r for r in ROBOTS if r["category"] == "available"]


def waitlist_robots() -> list[dict]:
    return [r for r in ROBOTS if r["category"] == "waitlist"]
