name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-azure-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create deployment package
      run: |
        cd backend
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        
    - name: Zip artifact for deployment
      run: |
        cd backend
        zip -r ../deploy.zip . -x "venv/*" "*.pyc" "__pycache__/*" ".env"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'botlease-backend'  # VERVANG DIT MET JOUW APP NAAM
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip